### ISSUE TITLE
What's different form r2? ⚡️👐

### ISSUE THREAD

**Issue by antonmedv** [sindresorhus/ky#10]
https://www.npmjs.com/package/r2

**Comment by szmarczak** [comment]
It's an early release. There's no major difference yet, but soon there'll be many useful features which `r2` doesn't provide.

**Comment by szmarczak** [comment]
@sindresorhus `r2` is built for browsers too. It uses `node-fetch` as a polyfill.

**Comment by sindresorhus** [comment]
@szmarczak You're right. I only read the first part of the text. Updated.

**Comment by borisrorsvort** [comment]
Aside from comparaison table, if you think these differences are better, why not discussing them between library makers and choose one existing one and make it stronger & reliable lib. So that everybody can commit and improve without fearing it gets abandonned next year? Some libs are much older and their makers dont have @sindresorhus  exposure, though this lib is heavily inspired by them.

**Comment by sindresorhus** [comment]
@borisrorsvort I first started this project more than a year ago as an experiment to see how I could reimagine [Got](https://github.com/sindresorhus/got) if it were built for the browser and based on Fetch. It's solely inspired by Got and Fetch. I only just recently had the time to finish it up and publish it.

It's not clear what libs you're referring to, but if you can share, I can elaborate more. If you mean `r2`, I had not seen it before it was mentioned here, but it's also clearly not maintained anymore, so trying to contribute to it would not be very productive.

---

> without fearing it gets abandonned next year?

I have 1K+ npm packages and I actively maintain them all. I've been doing open source for many years and I don't see that changing. I'm in for the long haul. I'm supported by the community to work on [open source full-time](https://www.patreon.com/sindresorhus). I created Got in early 2014 and it's still actively maintained. Ky also has another maintainer and hopefully even more additional maintainers in the future. I hope this addresses your concerns.

**Comment by sindresorhus** [comment]
> There is elbywan/wretch for instance.

Its overly chainable API would be a dealbreaker for me personally. I don't see anyway they would change that.

> My comment wasn't in no way intended to question the quality of your work which I deeply respect but more as a general remark about the js ecosystem.

I did not take it as that. I just wanted to elaborate on why Ky will not end up being abandoned like a lot of projects in the JS ecosystem, which I totally agree is a big problem.

**Comment by joseluisq** [comment]
One of the most significant differences is [latest browsers support](https://github.com/sindresorhus/ky#browser-support) by default.
