### ISSUE TITLE
Why node >= 10 is required ?

### ISSUE THREAD

**Issue by titouancreach** [sindresorhus/ky#102]
Hello,
After creating an app using react-create-app, I added `ky` using `yarn add ky`. I got this error:
```
error ky@0.8.0: The engine "node" is incompatible with this module. Expected version ">=10".
error Found incompatible module
```
(with my current nodejs version === 8).

So I wondering why node 10 is required to install the package ?

Thanks

**Comment by sindresorhus** [comment]
Because it uses the `URL` global which is only available in Node.js 10 or later.

**Comment by titouancreach** [comment]
Yes but `ky` is supposed to run in a browser environment, not a Node.js one, so why Node.js version matter ?

**Comment by szmarczak** [comment]
> Node.js version matter ?

Because you can also run Ky in Node - you need to use polyfills.

**Comment by titouancreach** [comment]
Ok I understand better. The problem is that "yarn" block the installation even if I want to install `ky` in a browser environment and I have the polyfill setup already via babel

**Comment by sholladay** [comment]
IIRC, I believe we work on Node 8 as long as the user does `global.URL = url.URL`. So we could consider relaxing the minimum version and say that's part of the polyfill steps.

Either way, Yarn"s behavior here is problematic, because while Yarn correctly detects our minimum Node version, it doesn't understand that we don't _require_ Node. This is going to be an issue for most libraries that support multiple encirinments. If Yarn wants to be so strict, then it needs to provide a way for the end user to specify their target environment(s) for Yarn to validate against.

Someone who uses Yarn should open an issue over there.

**Comment by somebodytolove** [comment]
> IIRC, I believe we work on Node 8 as long as the user does `global.URL = url.URL`. So we could consider relaxing the minimum version and say that's part of the polyfill steps.

Hello @sholladay, where do I need to set the global to get support for Node 8? How about URLSearchParams?

BTW I am using the brand-new [ky-universal](https://github.com/sindresorhus/ky-universal) thanks @sindresorhus.

**Comment by sholladay** [comment]
There's no special place. Ky looks in the global scope for those APIs that need to be polyfilled. So in Node you would simply assign any necessary polyfills to `global.URL`, `global.URLSearchParams`, etc.

**Comment by callumlocke** [comment]
@sholladay:

> If Yarn wants to be so strict, then it needs to provide a way for the end user to specify their target environment(s) for Yarn to validate against.

I kind of agree, and maybe they'll change it in future. But in the meantime, what tangible benefit does the `"node": ">=10"` line bring to Ky? If nothing much, then I would really like to see that line removed so I can use Ky in my yarn/node8 project.

cc @sindresorhus - I would really appreciate if you would reconsider this.

**Comment by szmarczak** [comment]
Use [`ky-universal`](https://github.com/sindresorhus/ky-universal) (Node 10 is stil required). For Node 8 we would need to do:
```js
const {URL, URLSearchParams} = require('url');

global.URL = URL;
global.URLSearchParams = URLSearchParams;
```

@sindresorhus Maybe it's worth to do that?

**Comment by sindresorhus** [comment]
No, because the require call causes problems with Webpack...

**Comment by szmarczak** [comment]
I mean to do that in `ky-universal`...

**Comment by sindresorhus** [comment]
`ky-universal` can be used with Webpack too. Hence the `universal` part. It works in *both* Node.js and the browser.

See: https://github.com/webpack/webpack/issues/8826

**Comment by sholladay** [comment]
Would Yarn respect it if we added `engineStrict: false`? I remember this field from npm"s early days. npm stopped paying attention to it, but maybe Yarn supports it and just defaults to `true`. That might be slightly closer to the semantics we are hoping for. It would hopefully log a warning instead of an error.

**Comment by szmarczak** [comment]
@sindresorhus But you do use `require` there already

**Comment by sindresorhus** [comment]
@szmarczak That's different. Those are requiring dependencies, not core modules.

**Comment by sindresorhus** [comment]
@sholladay No idea.

**Comment by szmarczak** [comment]
@sindresorhus Should it return the window.URL?

**Comment by sindresorhus** [comment]
@szmarczak Not sure what you're asking?

**Comment by szmarczak** [comment]
I mean is `require('url').URL` the same as `window.URL`?

**Comment by sindresorhus** [comment]
In Node.js, yes, but Webpack is not smart enough to know that. Webpack runs every `require` it finds, even if it's behind an if-statement.

**Comment by szmarczak** [comment]
Oh... So agreed, let's keep it this way for now...
