### ISSUE TITLE
Usage in web-app

### ISSUE THREAD

**Issue by mesqueeb** [sindresorhus/ky#103]
I have a general newbie question. Sorry to bother you with this!

1. If I create a web-app via a framework like VueJS. And I have to choose if I will use GOT or Ky, is it correct to go for Ky, when my app will be hosted as a single page application?

2. How about when I wrap this web-app into an iOS app with Cordova, which is basically a webview. Is this also considered as "browser" in this case, since it's a webview?

Will GOT also not just work in the above two cases because webpack does some magic when bundling an app?

Thanks a lot!

(i will close immediately as it's not an issue, but would greatly appreciate any advice!)

**Comment by sindresorhus** [comment]
For both `1.` and `2.`, Ky is the right choice. Got is great for Node.js, but bundling it for web, while it works, includes a lot of bloat as Webpack has to polyfill all the Node.js APIs.

**Comment by mesqueeb** [comment]
@sindresorhus Thanks so much for the intel!
One more followup question then:

If I opt for Ky instead of GOT, could I still use only Ky for things like tests via AVA etc.? Since I think that tests are run on Node if I'm correct. Or would I have to swap out Ky for GOT via dependency injection in the case of tests?

**Comment by sindresorhus** [comment]
> If I opt for Ky instead of GOT, could I still use only Ky for things like tests via AVA etc.?

Yes. see https://github.com/sindresorhus/ky#how-do-i-test-a-browser-library-that-uses-this

**Comment by sholladay** [comment]
Re: Usage of the `module` field in package.json, there is some relevant discussion here:

https://github.com/sindresorhus/ky/pull/81

In short, I think we'd be open to using `module`, especially if CDNs get on board. But right now we're not using it because we give preferential treatment to ESM users loading via CDN.

**Comment by sindresorhus** [comment]
> So I wonder why you didn't decide to build both GOT's codebase and Ky's codebase into 1 package and have them build the result in separate files that are then defined like I mention above in `package.json`.

Got and Ky have completely different APIs and different features. They were also built at separate times. I started Got many years ago. Ky was released recently.

**Comment by aristofun** [comment]
@sindresorhus  is there any performance benefits for using Ky in nodejs 20+ vs Got if I don't care about advanced features but do many server to server network calls?

**Comment by sindresorhus** [comment]
I don't have any performance benchmarks, but I would generally recommend using Ky. It's more stable and future-proof as it's built on Fetch (which on Node.js is built on Unidici, which is a more modern HTTP solution than what Got is built on).
