### ISSUE TITLE
Ky function does not accept arbitrary method Typescript typings

### ISSUE THREAD

**Issue by alexandercerutti** [sindresorhus/ky#106]
Hello! Thank for this awesome package!
I started using it for a component in the project I'm working on. Let me illustrate my case:
I have this class, with all static methods and props

```typescript
class M {
    static A() {
        return M.request("get", ...arbitraryParams: any[]) { ... }
    }

    static B() {
        return M.request("post", ...arbitraryParams: any[]) { ... }
    }

    static C() {
        return M.request("delete", ...arbitraryParams: any[]) { ... }
    }

    static request(method: string, ...arbitraryParams: any[]) {
        const response = await ky(M.url, {
            headers: {...},
            method,
       });

       /* ... more ... */
    }
}
```

All the methods call a specific one, `request`. Every method defines a method to make a call to the same URL (like a classic API).

I have a problem: I'm using Typescript and the method `ky()` accepts as method a type `OptionsWithBody | OptionsWithoutBody`. I saw the differences in the typings file and I saw that the difference is specific. But the problem is this: since I have a common method to make the requests and manage their result, I inserted a "method" parameter in `.request`, but I cannot pass it to the function as I get following error:

`Type 'string' is not assignable to type '"get" | "post" | "delete" | "head" | "put"'. ts(2322)`

So, What The F**k?!

I tried to set my request method as follows:

```typescript
static request(method: "get" | "post" | "delete" | "head" | "put", ...arbitraryParams) { ... }
```

But still

```
Argument of type '{ method: "get" | "post" | "delete" | "head" | "put"; headers: { ... }' is not assignable to parameter of type 'OptionsWithoutBody | OptionsWithBody'.
  Type '{ method: "get" | "post" | "delete" | "head" | "put"; headers: { ... }; }' is not assignable to type 'OptionsWithBody'.
    Types of property 'method' are incompatible.
      Type '"get" | "post" | "delete" | "head" | "put"' is not assignable to type '"post" | "delete" | "put"'.
        Type '"get"' is not assignable to type '"post" | "delete" | "put"'. ts(2345)
```

So, what to do?
It seems like the only way to decide the method, is to make a switch but this is a bad solution.

Thank you very much.

**Comment by alexandercerutti** [comment]
@sindresorhus, sorry for the tag, but I was looking at the code and still don't understand why in the typings, we have to differentiate `OptionsWithBody` from `OptionsWithoutBody`. I mean, for the code, it seems to be no such need. Or is there something I still not getting? Thank you.

**Comment by sholladay** [comment]
The distinction is due to the fact that `GET` requests should not have a body. The types are designed to prevent user mistakes.

**Comment by alexandercerutti** [comment]
So the only way to use the method I need, is to use the switch...

**Comment by sholladay** [comment]
There's probably a better solution. I'm just explaining why it's typed that way.

**Comment by alexandercerutti** [comment]
Yeah, okay. Meanwhile I thank you 😊

**Comment by SleeplessByte** [comment]
What @sholladay says is correct. Unfortunately these types are also not exported (when I last checked).

[This](https://github.com/SleeplessByte/useKy/blob/master/index.ts#L64) is how I solved it in my custom hook, using the [KyOptions](https://github.com/SleeplessByte/useKy/blob/master/index.ts#L7) manually.

TypeScript then understands that when I use `'get' | 'head'` as method, it will _not_ have a body and it will have a body otherwise.

**Comment by alexandercerutti** [comment]
I'm sorry for the delay, @SleeplessByte.
Yeah, they are still not exported. So you are saying that by doing this way, you can do this without a switch block?

**Comment by SleeplessByte** [comment]
Yes, basically in TypeScript if your give it a union of limited options, it will figure it out for you:

```typescript
type All = A | B

interface A {
  foo: 'bar'
  food: string
}

interface B {
  foo: 'foobar'
  lucky: number
}

function test(option: All) {}
```

Now if you call `test` with `test({ foo: 'foobar', ...` it will correctly start suggesting only "lucky".

**Comment by alexandercerutti** [comment]
I've not resolved but the problem got out of my focus as was a current work project problem. And for another issue I'm going to open, I'll probably have to leave Ky.
