### ISSUE TITLE
Question. How in proper way use ky-universal in case of moving off Request?

### ISSUE THREAD

**Issue by CrispusDH** [sindresorhus/ky#109]
We want to move off Request in [webdriverio](https://github.com/webdriverio/webdriverio). Two main objectives that we want to have are:
- lightweight
- work in both `Node.js` and `Browsers`

I think about trying `ky-universal` library, because `Got` for server only and `Ky` for browsers only.

I want to start with [this file](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/src/request.js). But I don't know how to deal with [agent option](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/src/request.js#L47). And I think it is not last thing that I will face.

Could you give me an advice? Is it good idea to take `ky-universal` or better option in my case will take another HTTP library?

**Comment by szmarczak** [comment]
`ky` aims for browsers. `ky-universal` just makes `ky` compatible with Node, it doesn't add new features like an `agent` option.

**Comment by CrispusDH** [comment]
thanks @szmarczak . Could you advice what library to choose?

**Comment by CrispusDH** [comment]
thanks again for answering
