### ISSUE TITLE
Support accessing options in afterResponse hook

### ISSUE THREAD

**Issue by kangkai124** [sindresorhus/ky#114]
There is a case where I need to behave differently in afterResponse hook according to the parameters passed in options, so access options in afterResponse hoook is very useful.

It is an example, I extend ky, when error occurs, global messages can be display or not according to `silent` passed in `_ky.get()`.
```js
const _ky = ky.extend({
  hooks: {
    afterResponse: [
      (res, { silent }) => {
        if (!res.ok && !silent) {
          // display global messages...
        }
        return res
      }
    ]
  }
})

_ky.get('example.com/api/xx', { silent: false })  // if error occurs, global message will display
_ky.get('example.com/api/xx', { silent: true })   // if error occurs, global message will not display
```

**Comment by szmarczak** [comment]
Closing in favor of #116
