### ISSUE TITLE
Support access input, options in hooks

### ISSUE THREAD

**Issue by Astray-git** [sindresorhus/ky#116]
I'm trying to replace axios with ky:

Can you please you provide `input`, `options`(from user, not the one for `fetch`) as additional params for both hooks.
I want them to do some logging with `url` or add custom identifiers to requests.

related: #100, #114

**Comment by kangkai124** [comment]
See pr: [#115](https://github.com/sindresorhus/ky/pull/115)

**Comment by sholladay** [comment]
Is it okay if `input` has `prefixUrl` attached to it? Or do you really need the original `input`?

**Comment by Astray-git** [comment]
Yeah, in `afterResponse` I have the `url`. I need it in `beforeRequest` hook.

My use case: start a timer in `beforeRequest` using url as identifier and stop it in `afterResponse`. I can build a loading indicator using the timer.

**Comment by desislavsd** [comment]
I also need this one. For example I want in beforeRequest to be able to replace the `/api` part of the input with the url of my my API. This way I will be able to make local requests passing `/locales` and requests to the API passing `/api/users`.

**Comment by sindresorhus** [comment]
Fixed by #163
