### ISSUE TITLE
Edge support

### ISSUE THREAD

**Issue by alexandercerutti** [sindresorhus/ky#119]
Hello everybody!
I'm using Ky on an important project at work. Sadly I have to support also Edge but it seems Ky does not support it. Is there a specific reason? Will it be supported? Or at least, will the TRIDENT version of Edge - until Microsoft will release Chromium-based Edge?

Thank you very much.

**Comment by sindresorhus** [comment]
It's in the readme:

> For older browsers, you will need to transpile and use a fetch polyfill.

"Older browsers" meaning Edge too. No plan to do anything else for Edge.

**Comment by sholladay** [comment]
Edge supports all, or nearly all, of the things we depend on, so it should be pretty easy to fix whatever is broken in Edge. I'd be happy to work on this. Can you provide any details about what's not working?

My first guess is lack of support for one of the [globals we use](https://github.com/sindresorhus/ky/blob/8d295b0072c1733d722a9355f06dd370c469e160/index.js#L24-L28). In particular, I was suspicious that Edge might not yet have `AbortController`. But according to MDN, it was added in Edge 16. Is it possible that you are on an older version of Edge?

**Comment by alexandercerutti** [comment]
Thanks for the reply @sindresorhus.
That was absolutely not clear, as even if it's not one of the best browser, Edge shouldn't be considered as an older one imho.
Anyway, it was giving me syntax error... I don't know if the polyfill would make any difference...

@sholladay, as I said it gave syntax error on something like response result (an object with rest operator + [key], literally).

I don't remember anything else and I won't be able to see the code until Monday...

**Comment by sholladay** [comment]
Did you import Ky as a module or just with a normal `<script>` tag? Forgetting to import as a module is an easy mistake to make that will lead to a syntax error. You can use the UMD build if you can't or don't want to use Ky as a module for some reason.

**Comment by alexandercerutti** [comment]
No, I'm using it in a Typescript project, which is web-packed along with other projects and run on React+Babel+Typescript.
For this reason, my first idea was to let babel transpile this module, but it didn't work (also, I never used Babel)

**Comment by sholladay** [comment]
Okay I tried this out for myself and indeed, Edge chokes on Ky's syntax. Specifically, the stack trace points to [this line](https://github.com/sindresorhus/ky/blob/8d295b0072c1733d722a9355f06dd370c469e160/index.js#L49) as the cause of the syntax error.

That line uses object spread, which apparently isn't supported by Edge yet, [according to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax). Go vote for [this issue](https://github.com/Microsoft/ChakraCore/issues/3406) on their Chakra engine to let them know you want it. When that's released, Ky will hopefully "just work".

Until then, it would indeed be possible to transpile Ky with Babel. You'll have to configure it to do so explicitly, since by default, Babel will ignore things inside of `node_modules`.

**Comment by alexandercerutti** [comment]
Awesome, thank you very much!
Any clues how to tell it explicitly?

**Comment by sholladay** [comment]
Look at the `include` and `exclude` options to tell Babel what to process.

If I remember right, I think I had to tell it to exclude everything in `node_modules` except for the specific library I wanted to transpile.

**Comment by alexandercerutti** [comment]
I'll try on Monday, but I'm not sure I'll be able to do this. Is any Babel extension needed?

**Comment by sholladay** [comment]
Your Babel config probably already includes the necessary plugin, [@babel/plugin-proposal-object-rest-spread](https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread), but you can always try adding it just in case. The main problem is that Babel is ignoring `node_modules`, so you need to ensure your config tells Babel to include `node_modules/ky/**.js`.

This is not s problem with Ky. You will encounter the same problem with any library that uses modern syntax unless your build system is setup to handle it.

**Comment by alexandercerutti** [comment]
@sholladay, I've solved this way:

```javascript
// Webpack configuration file

module: {
    rules: [{
        test: /\.(js|jsx)$/,
        use: 'babel-loader',
        exclude: /(node_modules(?!\/ky)|bower_components)/,
    }, {
        ...
    }]
}
```

**Comment by ux-engineer** [comment]
At some point after Vue CLI plugins upgrade to 4.0 and 4.1 our Edge support got broken. Just found out that adding this in **vue.config.js** helped:

```js
  transpileDependencies: [
    'ky',
  ],
```
