### ISSUE TITLE
Object spread operator is breaking in local dev

### ISSUE THREAD

**Issue by dangdennis** [sindresorhus/ky#13]
# ❔ Issue

Ky is breaking due to the use of Object Spread Operator. 

## 🔦 Context

I've tested it with Create-React-App. CRA supports the Object Spread Operator, however if it's used within a module, Babel does not transpile it. Interestingly enough, Ky works fine when I add into a box at Codesandbox.io.

## 💻 Error Sample

```
./node_modules/ky/index.js
Module parse failed: Unexpected token (21:19)
You may need an appropriate loader to handle this file type.
| 				}
| 
| 				returnValue = {...returnValue, [key]: value};
| 			}
| 		}
```

## 🌍 Your Environment

Create react app @ latest
Node @ v10.6.0

**Comment by szmarczak** [comment]
> because the library isn't being ran into webpack/parcel.

It doesn't have to. Are you sure you're on Node 10?

**Comment by dangdennis** [comment]
I'd expect it to work as well. I just installed the latest Node to upgrade from 10.6 -> 10.9. Oh well, I'll chalk it up to my environment. And see what I can do.

**Comment by dangdennis** [comment]
If you or anyone would like to try the test app locally, here's what I was testing with.
https://github.com/dangdennis/ky-cra-test

**Comment by sindresorhus** [comment]
https://www.google.co.th/search?q=create+react+app+object+spread&oq=create+react+app+object+spread&aqs=chrome.0.0l2.6086j0j1&sourceid=chrome&ie=UTF-8

**Comment by watch2raff** [comment]
I have this problem to. My version node - v8.9.3
If i want use ky, i must  install version 10 ?

**Comment by dangdennis** [comment]
Hey @watch2raff ,

How are you using the package? Mine was breaking due to some problems with Babel 7 and npm symlinking.

**Comment by sarneeh** [comment]
Having the same error while using it with [next.js](https://github.com/zeit/next.js).

**Comment by iGanza429** [comment]
Same problem.

**Comment by sarneeh** [comment]
The reason is that `ky` does not provide a precompiled ES5 module. Created a separate issue for that: https://github.com/sindresorhus/ky/issues/28

**Comment by watch2raff** [comment]
> Hey @watch2raff ,
> 
> How are you using the package? Mine was breaking due to some problems with Babel 7 and npm symlinking.

I using this package in my app create with create-app-react.
