### ISSUE TITLE
Passing a Request object as first argument to ky fails

### ISSUE THREAD

**Issue by tatablack** [sindresorhus/ky#134]
I don't know if this is intentional, but the README - and the TypeScript definitions - state that in `ky(input, options)` `ky` accepts the same values as `fetch`.

However, passing a Request instance as the value for `input` does not work, since it's stringified [here](https://github.com/sindresorhus/ky/blob/master/index.js#L171) and it turns into `[object Request]`.

**Comment by sholladay** [comment]
Yep, confirmed, this is a bug introduced by PR #11. Thanks for reporting it!

The reason we stringify the input is to support passing in a WHATWG [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) instance. Those objects stringify to the appropriate URL, whereas `Request` objects do not.

The solution will involve checking `this._input instanceof Request`, and if true, use the value of `this._input.url` during construction of the prefix URL.
