### ISSUE TITLE
Headers options bug

### ISSUE THREAD

**Issue by niftylettuce** [sindresorhus/ky#137]
If you pass an instance of `new Headers({ ... })` as the value for `headers` it will cause the object to become empty.

<img width="967" alt="Screen Shot 2019-06-10 at 5 25 51 PM" src="https://user-images.githubusercontent.com/523141/59230983-d1119a80-8ba4-11e9-8e62-d0c9dac06682.png">

Ref: https://github.com/sindresorhus/ky/blob/master/index.js#L205

**Comment by sholladay** [comment]
I suppose you are basing this on the `{}` part of `Headers {}` in the debug output of the console? The console is deceiving you. :)

```js
const x = new Headers(new Headers({ foo : 'bar' }));
x.get('foo');
// => "bar"
```

We have tests for this here: https://github.com/sindresorhus/ky/blob/07838c79e66b74f4d365b4c5ac82c5c9c18039b8/test/main.js#L132-L154

**Comment by niftylettuce** [comment]
Nice.
