### ISSUE TITLE
delay causes node process to hang

### ISSUE THREAD

**Issue by jamime** [sindresorhus/ky#138]
This package and [ky-universal](https://github.com/sindresorhus/ky-universal) is used in [danger-js](https://github.com/danger/danger-js) via the [node-gitlab](https://github.com/jdalrymple/node-gitlab) project.

When ky is used, the node process will not exit until the `setTimout` has completed. 

https://github.com/sindresorhus/ky/blob/07838c79e66b74f4d365b4c5ac82c5c9c18039b8/index.js#L122

I suggest changing the `delay(ms)` function to accept a promise `delay(ms, promise)` when the promise is resolved the timeout can be cancelled. In this instance the promise needs to be the promise copied into timeout.

https://github.com/sindresorhus/ky/blob/07838c79e66b74f4d365b4c5ac82c5c9c18039b8/index.js#L127

This bug was introduced in #122

**Comment by sindresorhus** [comment]
// @arty-name

**Comment by arty-name** [comment]
Since `setTimeout` existed in code before #122 I don’t really understand why it didn’t break things then. 

My instinct would be to avoid using `delay` as a wrapper for setTimeout and instead use setTimeout directly. This would allow calling clearTimeout when the promise is settled. It would be a bit less elegant though. 

Alternatively we could do something like this: 

```javascript
function awaitWithTimeout(promise, timeout) {
  return new Promise((resolve, reject) => {
    const timeoutHandle = setTimeout(() => reject(new TimeoutError()), timeout);
    // eslint-disable-next-line promise/prefer-await-to-then
    promise.then(resolve).catch(reject).then(() => clearTimeout(timeoutHandle));
  })
}

// eslint-disable-next-line promise/prefer-await-to-then
const timeout = (promise, ms, abortController) => awaitWithTimeout(promise, ms).catch((error) => {
  if ((error instanceof TimeoutError) && abortController) {
    abortController.abort();
  }
  throw error
})

**Comment by jamime** [comment]
Ah, my mistake. I thought it was introduced in #122 Looks like this bug did exist before then.

**Comment by obartra** [comment]
looks like `delay` is only used in two spots, I'm happy to make the change `arty-name` suggest if no-one is working on it. I'm running into the same issue @jamime describes

**Comment by jamime** [comment]
@obartra I'm not looking at it, if you have time that would be great.

**Comment by szmarczak** [comment]
@arty-name 

> Alternatively we could do something like this:

Yup, that would work. Clearing the timeout would fix browsers and Node. If someone's looking for Node-only solution then he needs `timeout.unref()`.
