### ISSUE TITLE
Size seems out of date

### ISSUE THREAD

**Issue by stramel** [sindresorhus/ky#140]
README.md states "1 KB (minified & gzipped)" but BundlePhobia is showing 2.3KB. https://bundlephobia.com/result?p=ky@0.11.1

If size of the package is important would it be beneficial to add `bundlesize` travis integration?

**Comment by sholladay** [comment]
The [CDN link](https://cdn.jsdelivr.net/npm/ky/index.min.js) is the only one that matters significantly in terms of size, I would say. Firefox's Network tab is telling me it is 3.11KB over the wire. Still seems okay, but yeah that number is out of date.

I guess a good solution would be a readme badge that displays a live number.

**Comment by stramel** [comment]
Thank you for the quick follow up!
