### ISSUE TITLE
Promise never/rarely resolves

### ISSUE THREAD

**Issue by tiagosiebler** [sindresorhus/ky#142]
After the workaround from #141, this is working well for all endpoints I've mapped into function calls, except one. The difference in this call is that it returns roughly 300kb of JSON, and may take around 500ms to complete.

For some reason this promise rarely resolves. I've got logging printing out up until the call itself, which seems to hang indefinitely. Other calls can happen fine in parallel (testing using a chat bot), but this call always starts and very rarely completes. 

What's weirder, it's working sometimes on my laptop (connecting to API on remote server), but usually it never works on the remote server (same one hosting the API), doesn't matter whether I use localhost or the domain for the API url.

I've tried simplfying as much as possible and included a progress fn, in the off chance it's network - but nothing seems to happen after the request starts:
<img width="811" alt="Screenshot 2019-06-18 at 11 33 50" src="https://user-images.githubusercontent.com/14090872/59675388-147b9280-91bd-11e9-90d2-3d037625f0aa.png">

<img width="576" alt="Screenshot 2019-06-18 at 11 33 57" src="https://user-images.githubusercontent.com/14090872/59675397-16ddec80-91bd-11e9-99a6-f77e94b6190f.png">

Any idea what might be going on? How can I troubleshoot this to pin down the hang?

**Comment by tiagosiebler** [comment]
Should add that this is for a node process, with node-fetch forced on due to #141.

**Comment by sholladay** [comment]
I cannot reproduce this  Could you make a demo of the problem on CodeSandbox?

Both of these issues _seem_ environmental to me. Perhaps something to do with `node-fetch` and the way it is being imported/initialized? Or a missing `.catch()` handler? Just a stab in the dark.

Is there a reason you don't want to use `got` in Node instead? It's generally going to be a better choice, at least for now - more features and it is specifically designed for Node, as opposed to `ky`, which is designed for the browser. While `ky` should technically be usable in Node, it requires multiple hacks, and I can't help but wonder if one of them is giving you trouble.

**Comment by tiagosiebler** [comment]
> Is there a reason you don't want to use got in Node instead? It's generally going to be a better choice, at least for now - more features and it is specifically designed for Node, as opposed to ky, which is designed for the browser. While ky should technically be usable in Node, it requires multiple hacks, and I can't help but wonder if one of them is giving you trouble.

Was hoping for a universal API wrapper for both CLI and frontend, as that would be less to maintain. Seems this is only happening in CLI and only sometimes. Will close this until I have an easy way to reproduce with non-sensitive data.

**Comment by sholladay** [comment]
This issue seems suspiciously similar to https://github.com/sindresorhus/ky-universal/issues/8. You may want to keep an eye on that one, especially if you are using `ky-universal`.
