### ISSUE TITLE
猫の額爪の垢を煎じて飲む sounds so strange as the description of this library

### ISSUE THREAD

**Issue by kt3k** [sindresorhus/ky#150]
The line under the logo reads "猫の額, 爪の垢を煎じて飲む".

I believe these are 2 Japanese idioms, but these don't make any sense to me as the description of this library. And therefore this line is very misleading for Japanese audience.

(Note: This literally means "The forehead of a cat drinks the dirt under the fingernail (of someone noble)")

How about changing this to "極楽要求(しなさい)" (meaning "make a delightful request")?

**Comment by sindresorhus** [comment]
Sure, I was just trying to be weird in Japanese.

**Comment by kt3k** [comment]
Hmm, but some of my friends actually confused by that title and avoided trying this library. That looked unfortunate...

**Comment by sindresorhus** [comment]
Yeah, I'm happy to change to what you proposed. Just out of curiosity, why is the Hiragana part in parenthesis?

**Comment by kt3k** [comment]
> why is the Hiragana part in parenthesis?

Good question! The parens are unusual, but that's inspired by Superdry's usage of `極度乾燥(しなさい)`. (Superdry is a British clothing company and they use Japanese tag line in a similar way to this library. `極度乾燥(しなさい)` was phenomenal in Japan. Parenthesized `(しなさい)` shows a homage to their attempt and has (maybe) a little funny effect. cf. https://en.wikipedia.org/wiki/Superdry

**Comment by sindresorhus** [comment]
Ah, I see. Yes, that's fun. I really appreciate your suggestion. This is much better.

**Comment by kt3k** [comment]
@sindresorhus Thank you for taking my suggestion! 😄

**Comment by oudoulj** [comment]
By the way,how do you pronounce the name of the library Ky ?
And what does it mean ? 😃

**Comment by sholladay** [comment]
@oudoulj for the meaning, see:
https://github.com/sindresorhus/ky/blob/master/readme.md#what-does-ky-mean

In English, I would pronounce it like the "c" in "car", followed by "eye".
