### ISSUE TITLE
Should be `prefixUrl` prepended if `input` is a URL instance?

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/ky#152]
See https://github.com/sindresorhus/got/pull/829#pullrequestreview-260908732

**Comment by sholladay** [comment]
Absolute URLs, that is. `URL` instances happen to always be absolute, at time of writing (hopefully they will support relative URLs in the future)..

**Comment by szmarczak** [comment]
I think it **should** be prepended. It can be easily turned off by using `prefixUrl: ''`.
