### ISSUE TITLE
[feature request] support array of query string parameters in get request

### ISSUE THREAD

**Issue by dabuside** [sindresorhus/ky#155]
In some case, we would want to do 
```
ky.get('someURI',{searchParams: array:[0,1]}) //which is not allowed
```
https://github.com/sindresorhus/ky/blob/64e93c5da5874ca4010044c3439a018f350483d8/index.d.ts#L52
https://github.com/sindresorhus/ky/blob/64e93c5da5874ca4010044c3439a018f350483d8/index.js#L194-L205
In angularJS or something will warp them as `?array=0&array=1` which is very convenience.
I am wondering if it can be supported.

**Comment by sholladay** [comment]
Isn't this similar to https://github.com/sindresorhus/got/issues/638?

To convert a simple array of key/value pairs, you can just pass the array to `new URLSearchParams()`. For array values within an individual query property, we probably won't support that, as mentioned in the linked issue.
