### ISSUE TITLE
Skipping request by returning a Response in beforeRequest

### ISSUE THREAD

**Issue by hugomrdias** [sindresorhus/ky#157]
This could be useful for internal caching, mocking, etc..
Would this be an acceptable feature ?

**Comment by sholladay** [comment]
Seems like an interesting idea. But I'm curious why the built-in caching mechanisms are not sufficient? You can specify the caching mode for each request.

See: https://developer.mozilla.org/en-US/docs/Web/API/Request/cache

**Comment by hugomrdias** [comment]
For my specific case I'm trying to reduce the number of parallel requests (due to browser limits) with a local cache. Don't ask why 😅.
Still this can be useful for other use cases and isn't too intrusive.

**Comment by sindresorhus** [comment]
Sounds useful. PR welcome.
