### ISSUE TITLE
TypeScript - Union `Options` complicates `ky` API

### ISSUE THREAD

**Issue by joaovieira** [sindresorhus/ky#164]
I've seen that was added in https://github.com/sindresorhus/ky/pull/87 to "fix" https://github.com/sindresorhus/ky/issues/85. While it works well on its own (i.e. when invoking `ky` or `ky.get`/`ky.post` shorthands), it complicates the usage of the `Options` type if you ever need to manipulate them.

Take my example, we're wrapping `ky` as we'd like to convert the `body`/`json` keys to snake case before sending to the server and vice-versa on response. Something like:

```ts
import { Input, Options } from 'ky';

export default async function (input: Input, options?: Options) {
  const kyOptions = { ...options };
  kyOptions.json = snakeCase(kyOptions.json); // error: property `json` does not exist on type `OptionsWithoutBody`
  
  try{
    const resp = await ky(input, kyOptions);
    return camelCase(resp.json);
  } catch (e) {
    ...
  }
}
```

However, given the current type of `Options = OptionsWithoutBody | OptionsWithBody` we cannot use `kyOptions.json` as it does not exist in `OptionsWithoutBody`. The compiler only allows access to that property once it knows it's of type `OptionsWithBody`, like so:

```ts
if (kyOptions.method && ['post', 'put', 'patch', 'delete'].includes(kyOptions.method.toLowerCase())) {
  kyOptions.json = snakeCase(kyOptions.json);
}
```

This is not ideal as the application would need to implement the same logic as `ky` to differentiate options with and without body based on the method.

---

On top of that, using an union type makes extending the options awkward. When using interfaces you do:

```ts
interface Options extends KyOptions { 
  snakeCaseTransform: boolean;
}
```

With union types it becomes:

```ts
type Options = KyOptions & {
  snakeCaseTransform: boolean;
}
```

---

As I also mentioned in #162, having this strict type prevents custom or non-whitelisted methods (e.g. `trace`), that are allowed by the spec and `fetch` itself:

```ts
ky('https://example.com', {
  method: 'custom',
});
```

Lastly, it is adding something not enforced by the implementation. The native `fetch` types don't do that discrimination.

---

Thus I want to propose to essentially revert https://github.com/sindresorhus/ky/pull/87 and use `Options` everywhere. This makes the API and types much simpler, easier to read and extend.

Thoughts? Happy to do it if agreed.

**Comment by joaovieira** [comment]
An alternative is to strict the `method` in the `Options` (we're already doing that implicitly in the union type anyway):

```ts
export interface Options extends RequestInit {
  method?: 'get' | 'head' | 'post' | 'put' | 'delete' | 'patch';
  ...
}

declare const ky: {
  (url: Input, options?: OptionsWithoutBody | OptionsWithBody): ResponsePromise;
  get(url: Input, options?: OptionsWithoutBody): ResponsePromise;
  post(url: Input, options?: OptionsWithBody): ResponsePromise;
  ...
}
```

This compiles fine as the `method` type is now compatible. I.e.:

After:
`'get' | 'head' | 'post' | 'put' | 'delete' | 'patch'` is assignable to `OptionsWithoutBody['method'] | OptionsWithBody['method]'`

Before:
`string` is not assignable to `OptionsWithoutBody['method'] | OptionsWithBody['method]'`

**Comment by sindresorhus** [comment]
Yeah, I'm starting to think it's not worth the complexity. It's nice to catch things at compile time instead of runtime, but TypeScript is not good enough yet to make this *not annoying* for users.

**Comment by joaovieira** [comment]
Added a PR with the first suggestion (using a single and same `Options` everywhere).
