### ISSUE TITLE
Modify the request URL in the `beforeRequest` hook

### ISSUE THREAD

**Issue by kahirokunn** [sindresorhus/ky#166]
I want to edit request url in the beforeRequest hook.
Thx.

**Comment by sindresorhus** [comment]
Have you tried? Or are you saying it's not working?

**Comment by szmarczak** [comment]
I think he meant the latter.

https://github.com/sindresorhus/ky/blob/83dff35a23a022e2c039ef2e1df966f619f9c206/index.js#L383-L387

https://github.com/sindresorhus/ky/blob/83dff35a23a022e2c039ef2e1df966f619f9c206/index.js#L226

Strings are immutable. We could pass `this` as the third argument, but that wouldn't be elegant.

**Comment by sholladay** [comment]
Perhaps we should allow `beforeRequest` hooks to return a [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) instance, which we would pass to `fetch()`. That would allow them to use any URL they want, as well as other options. Should be pretty easy to implement.

**Comment by pavel-kru** [comment]
couldn't rewrite url in beforeRequest as it "readonly"

**Comment by pavel-kru** [comment]
if anyone face to "url" is redonly you could do next:

`   
 beforeRequest: [
      (req, options) => {
        return ky(`${req.url}ANY_YOUR_UPDATES`, options);
      },
    ],  
`

**Comment by DaniilIsupov** [comment]
I also met this problem

**Comment by sholladay** [comment]
You don't modify the existing request (which is read only), you return a new one.
