### ISSUE TITLE
Fix Travis

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ky#168]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/ky/issues/168)

https://travis-ci.com/sindresorhus/ky/jobs/227726270

Travis is slow. I think we might just need to increase the Puppeteer timeout somehow.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#177 Fix Travis CI - Serialize Browser Test](https://issuehunt.io/r/sindresorhus/ky/pull/177)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/ky/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sholladay** [comment]
The three most recent Travis builds all failed in exactly the same way, always a TimeoutError and always on Node 10 but not Node 12. Seems kinda fishy, no? Also, it says the timeout is 30 seconds which seems pretty reasonable to me.

**Comment by sindresorhus** [comment]
Could be, but from experience, it's almost always Travis being slow, especially when the problem is only on older Node.js versions.

**Comment by szmarczak** [comment]
> Could also be a race issue in the code or test.

It's not definitely a race issue. I've experienced it also when developing `http2-wrapper`.

**Comment by Ybrin** [comment]
I will give this a try
