### ISSUE TITLE
Ky typescript, jest and es modules + temp solution

### ISSUE THREAD

**Issue by belgattitude** [sindresorhus/ky#170]
Spend few hours trying to make typescript, jest, lerna and ky to play well together.  Here's something that might help in case of:

```bash
    export default createInstance();
    ^^^^^^
    SyntaxError: Unexpected token export
    > 4 | import ky from "ky";
```

With Jest you can simply add it to the `transformIgnorePatterns`, but the way lerna works your node_modules will probably end up in the top level `node_modules`. So here's something that seems to works in every cases:

```js
    moduleNameMapper: {
        '^ky$': require.resolve('ky').replace('index.js', 'umd.js'),
    }
```

This way, jest choose the umd build instead of es one.

Warning, this assumes there will always be an umd.js build packaged with ky.

There might be better solutions, feel free to let me know yours

**Comment by sindresorhus** [comment]
I would try discussing this on the Jest support forums instead. Ky is just a normal ESM module. The problem lies in how complex Jest and Lerna are.

**Comment by belgattitude** [comment]
@sholladay 

> We have umd.d.ts with TypeScript types

Well, so `import ky from 'ky/umd'` will actually work (require is not the way to go in ts). But this way defeats the purpose of using esm. 

IMO, `Jest problem` => `should be fixed through jest configuration`. 

The jest way of fixing this is through `transformIgnorePattern` or `moduleNameMapper` till jest supports esm.  

> The most likely reason that ky is the only affected module in your stack is simply because there are not yet many other ES6 modules in the npm registry.

Yes but some popular ones: `lodash-es` being a good example. tree-shaking really matters here. They went another way, maintaining two repos: `lodash` and `lodash-es` but the same logic applies. The common solutions are either to use `transformIgnorePatterns` or `moduleNameMapper` to enable transpilation or map `lodash-es` to `lodash` (I prefer the later). So I guess people are used to do it.  

Regarding ky. 

I would just add a note in the doc or keep this issue as closed, so people would not spend time looking through SO or jest issues.

The trick I posted

```
moduleNameMapper: {
        '^ky$': require.resolve('ky').replace('index.js', 'umd.js'),
}
```

might be and unsexy overkill but does not affect your bundle and works with lerna too (that's where I spent time). 

But I would not document use of require, neither suggest to use `import ky from 'ky/umd'`, it's not about ky, rather about lack of esm support in Jest.

**Comment by ericnkatz** [comment]
Any way we can solve this issue related:
`Circular definition of import alias 'default'.` ?

**Comment by nfour** [comment]
I found to get this working with typescript and `ky` I had to do this:

I want to write this code:
```
import ky from 'ky';
```

So I configured jest with:
```
  moduleNameMapper: {
    '^ky$': '<rootDir>/.jest/ky.js',
  }
```

As the `umd` bundle doesnt export a default, at least in Jest, (yet the TS type says it does), I created `./.jest/ky.js`
```
exports.default = require('ky/umd');
```

Lot of effort but at least its inline with how the webpack bundle operates.

**Comment by riccardo-forina** [comment]
```
"moduleNameMapper": {
  "ky": "ky/umd"
}
```

this seems to work for me

**Comment by targumon** [comment]
@riccardo-forina Thanks for this simple solution!

however...

@sindresorhus [v0.26.0](/sindresorhus/ky/releases/tag/v0.26.0) broke it (because #315 - drop UMD).
So for now I'll stay at 0.25, but would really appreciate guidance on how to re-solve this.

**Comment by targumon** [comment]
Never mind, solved it with:

```
  transformIgnorePatterns: [
    '/node_modules/(?!(ky))'
  ]
```

(Explanation to whoever stumbles upon this thread like me: By default jest ignores `node_modules`. This configuration tells it: 'yeah, ignore anything in there, EXCEPT for ky'. If you have more dependencies like this, just replace `(ky)` with `(ky|other-deps|needing-transpilation)` [source: jestjs.io](https://jestjs.io/docs/en/tutorial-react-native#transformignorepatterns-customization))

Thanks for a great package!

**Comment by paulrostorp** [comment]
Using transformIgnorePatterns didn't work for me

**Comment by sholladay** [comment]
Don't forget to remove `moduleNameMapper` and any other workaround you were using previously.

For anyone who still can't get this to work, I suggest linking to a GitHub repo or CodeSandbox with a minimal reproducible example where we can all take a look and collaborate on the solution.

**Comment by robcaldecott** [comment]
This is not working for me either. I removed `moduleNameMapper` and added `transformIgnorePatterns`. I'm luck enough to be using `react-app-rewired` so have full control over the `jest` config but it looks like the default CRA config is causing the issue. If I log what `jest` is configured to use by default it looks like this:

```
transformIgnorePatterns: [
    '[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs|cjs|ts|tsx)$',
    '^.+\\.module\\.(css|sass|scss)$'
  ],
```

And If I modify this to:

```
transformIgnorePatterns: [
    '[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs|cjs|ts|tsx)$',
    '^.+\\.module\\.(css|sass|scss)$',
    '/node_modules/(?!(ky))'
  ],
```

Then it won't work, no matter what order the lines appear. However, if I replace it with this:

```
transformIgnorePatterns: [
  "^.+\\.module\\.(css|sass|scss)$",
  '/node_modules/(?!(ky))'
]
```

Then it works. I'll have to try it but I don't think replacing the entire config like this is an option for most CRA users.

**Comment by sholladay** [comment]
I'm happy to take a deeper look if someone posts a link to a minimal reproducible example. :)

**Comment by robcaldecott** [comment]
It does work with a `create-react-app` project 👯  but just note that using `transformIgnorePatterns` will completely overwrite the CRA defaults which might cause issues if you're using CSS modules because this gets removed:

```
'^.+\\.module\\.(css|sass|scss)$'
```

Here's a link to a sample repo.

https://github.com/robcaldecott/ky-jest

Run `npm test ky` to see it working.

**Comment by bugzpodder** [comment]
ReferenceError: globalThis is not defined

    >  9 | import ky from "ky";
    
    when I use transformIgnoreModules approach in CRA.  still trying to work out a solution

**Comment by sholladay** [comment]
@bugzpodder what environment is that error from?

**Comment by bugzpodder** [comment]
@sholladay I'm using latest CRA + React 17 + yarn 2 (berry) + pnp + ky 0.36.

**Comment by bugzpodder** [comment]
ok i figured it out, i am using node 10 and ky requires node >= 12, the globalThis error is from node 10.

**Comment by sholladay** [comment]
@bugzpodder I'm glad you got it working! Would you be willing to put up an example repo we can link to for people who are having trouble?

**Comment by bugzpodder** [comment]
It should be the same.  Use node 12 and the globalThis error should be gone.

**Comment by angeloashmore** [comment]
For anyone else coming across this when using Jest + TypeScript via `ts-jest`, this Jest config is working for me.

Note the inclusion of `ts-jest/presets/js-with-ts` rather than just `ts-jest`. This tells `ts-jest` to transform `.js` files in addition to `.ts`.

```
// jest.config.js

module.exports = {
  preset: 'ts-jest/presets/js-with-ts',
  transformIgnorePatterns: ['/node_modules/(?!(ky))'],
}
```

You will need to polyfill `fetch` in your tests if you don't already have it available globally:

```
import 'cross-fetch/polyfill'
```

**Comment by sholladay** [comment]
@angeloashmore we have [ky-universal](https://github.com/sindresorhus/ky-universal) to take care of polyfilling for you. I'd strongly recommend using that instead of polyfilling yourself, because there's more than just `fetch` that needs to be polyfilled in Node.

**Comment by angeloashmore** [comment]
@sholladay Thanks, I did try ky-universal but using it is not straightforward, at least with the combination of Jest, TS, and the version of Node I am using.

ky-universal shouldn't be transpiled, as recommended by you in another thread (sorry, not exactly sure where I read that earlier today). By transpiling using `ts-jest`, a top-level await is introduced, which throws the following error:

```
    /[redacted]/node_modules/ky-universal/index.js:25
            globalThis.ReadableStream = await Promise.resolve().then(() => tslib_1.__importStar(require('web-streams-polyfill/ponyfill/es2018')));
                                        ^^^^^

    SyntaxError: await is only valid in async function

      3 | import * as TE from 'fp-ts/TaskEither'
      4 | import { pipe } from 'fp-ts/function'
    > 5 | import ky from 'ky-universal'
        | ^
      6 |
      7 | import {
      8 |   BuildTypePathsStoreFilenameEnv,

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1350:14)
```

Not transpiling leaves in `import`s, which also cannot be run:

```
    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/angeloashmore/projects/js/gatsby-source-prismic/node_modules/ky-universal/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import fetch, {Headers, Request, Response} from 'node-fetch';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      3 | import * as TE from 'fp-ts/TaskEither'
      4 | import { pipe } from 'fp-ts/function'
    > 5 | import ky from 'ky-universal'
        | ^
      6 |
      7 | import {
      8 |   BuildTypePathsStoreFilenameEnv,

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1350:14)
```

The only difference between the two runs is singling out `ky` from `ky-universal` in the `transformIgnorePatterns` option:

```diff
  module.exports = {
    preset: 'ts-jest/presets/js-with-ts',
-  transformIgnorePatterns: ['/node_modules/(?!(ky))'],
+  transformIgnorePatterns: ['/node_modules/(?!(ky/))'],
  }
```

I don't doubt there's some combination of config that allows this, but I kind of gave up. Happy to provide more details if you're able to guide a correct setup.

**Comment by sholladay** [comment]
@angeloashmore your `transformIgnorePatterns` regex looks wrong to me. If you're using `ky-universal`, then that regex probably needs to exclude both `ky` and `ky-universal`. Your regex has `ky/`, which I believe will correctly exclude the path for `ky` but not `ky-universal`. I expect that something like `'/node_modules/(?!(ky|ky-unversal))'` should work.

You seemed to get a bit closer with the second error where it said "Jest encountered an unexpected token". That error links to docs on using ESM: https://jestjs.io/docs/en/ecmascript-modules

Based on those docs, it sounds like they want your app to also be in ESM mode (`"type": "module"` in package.json) in order to properly use an ESM dependency like Ky, because they're relying on the Node.js ESM loader to make those `import` statements work. If you already have that in your package.json, then I'm not sure what's wrong, but hopefully that helps. I also noticed that those docs suggest a slightly different way of disabling transforms than what people in this thread have been doing. Might be worth giving that a shot, too.

**Comment by jcace** [comment]
I managed to get it working by pasting the following into my `package.json`

```json
  "jest": {
    "transformIgnorePatterns": [
      "/node_modules/(?!(ky))"
    ],
    "moduleNameMapper": {
      "\\.(css|less)$": "identity-obj-proxy"
    }
  },

```

Although I'm not sure if this will break other tests down the road.. definitely a temporary solution for me

**Comment by alessandrojcm** [comment]
Hi there, I've tried the solutions on this issue but I can't seem to get it working. I'm stuck on the top-level await issue as @angeloashmore commented. My `jest.config.js`:

```javascript
const { pathsToModuleNameMapper } = require('ts-jest');
const { compilerOptions } = require('./tsconfig');

module.exports = {
    roots: ['<rootDir>/src'],
    transform: {
        '^.+\\.(ts|tsx|js|jsx)$': 'babel-jest',
        '^.+\\.svg$': '<rootDir>/svgTransform.js',
    },
    globals: {
        'ts-jest': {
            tsconfig: 'tsconfig.test.json',
            diagnostics: false,
            isolatedModules: true,
        },
    },
    testRegex: '(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$',
    testEnvironment: 'jest-environment-jsdom',
    setupFilesAfterEnv: ['<rootDir>/setupTests.ts'],
    collectCoverage: true,
    moduleFileExtensions: ['ts', 'tsx', 'js', 'json', 'jsx'],
    moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, { prefix: '<rootDir>/src/' }),
    testPathIgnorePatterns: ['<rootDir>[/\\\\](node_modules|.next)[/\\\\]'],
    transformIgnorePatterns: ['[/\\\\]node_modules[/\\\\].+\\.(ts|tsx)$', '/node_modules/(?!(@fullcalendar|ky|ky-universal)/)'],
};

```
As you can see, I already had a `transformIgnorePatterns` option set for the `@fullcalendar` package (also ESM),  it should work by just adding `ky` and `ky-universal`; although it does not. I've tried adding `type: module` to my `package.json` but this just causes all other sorts of things to break. Any ideas?

**Comment by sholladay** [comment]
@alessandrojcm my understanding is that if you follow [these instructions](https://jestjs.io/docs/ecmascript-modules), then `moduleNameMapper` (and probably a lot of that other stuff) becomes unnecessary.

**Comment by EmaSuriano** [comment]
For the people using CRA, the option of `transformIgnorePatterns` is not available when extending through the jest config. Therefore you are force to pass it as inline argument to the `test` script. Change your `test` command to: 
``` "test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!ky)/\"", ```
