### ISSUE TITLE
Validate input

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/ky#174]
Moved from #169

As of now, the input is not validated. It should throw if it's invalid (e.g. a number).

**Comment by himynameisdave** [comment]
Would be happy to pick this up, just point me to where I would need to start looking in the code 👍

**Comment by szmarczak** [comment]
You should validate the input before this line (or integrate it with the `if`):

https://github.com/sindresorhus/ky/blob/c4fe0c9f0f2aec8c1740f792dfa2164d93ec1f8c/index.js#L234

I would just change https://github.com/sindresorhus/ky/blob/c4fe0c9f0f2aec8c1740f792dfa2164d93ec1f8c/index.js#L245

to

```
} else if (!(input instanceof URL) && typeof input !== 'string') {
	throw new Error('...');
} else {
```
