### ISSUE TITLE
Remove headers

### ISSUE THREAD

**Issue by luq10** [sindresorhus/ky#189]
How can i remove header by extends another ky instance?

Something like this:
```javascript
const http = ky.create({
  headers: {
    authorization: 'Bearer TOKEN',
    otherHeader: 'value',
  }
});

const newHttp = http.extend({
  headers: {
    authorization: undefined // <- remove  Authorization header
  }
});
```

Ofc. this not work, this is only a showcase.

**Comment by whitecrownclown** [comment]
@luq10 You can do

```javascript

const newHttp = http.extend({
	headers: new Headers({}) // clear headers from `http`
});

```

**Comment by luq10** [comment]
@whitecrownclown Thanks for response :)

Yes i know about this, but in my case i want remove only `authorization` header, this `otherHeader` should stay.

**Comment by whitecrownclown** [comment]
@luq10 You could do

```javascript

const requestHeaders = new Headers({
	Authorization: 'basic 5tegso3',
	Pragma: 'no-cache'
});

const http = ky.create({
	headers: requestHeaders
});

// Dont need `Pragma` header for new `ky` instance
const newHeaders = requestHeaders.delete('Pragma');

const newHttp = http.extend({
	headers: newHeaders
});

**Comment by luq10** [comment]
Okay, so in this case i need to keep my headers in own variable.

This is some kind of weird, because if i want to add new header i can do just:

```javascript
const http = ky.create({
  headers: {
    authorization: 'Bearer TOKEN',
  }
});

const newHttp = http.extend({
  headers: {
    pragma: 'no-cache'
  }
});
// newHttp have both headers: 'authorization' and 'pragma'
``` 

Maybe you can think about this syntax:

```
headers: {
  [name]: undefined
}
```

to remove header in `extend`.

**Comment by sholladay** [comment]
My preferred solution would be to reverse the order of how you are extending Ky, such that you only ever add headers and never delete them.

In other words, the instance without the `authorization` header should be the base instance that you extend.

That said, I will give this some more thought. Maybe we should support `null` here, though I know Sindre tweeted somewhat recently about only using `undefined`. Seems a little awkward to me in this case.

Does `got` have this functionality?

A PR with a working implementation would be useful to further refine the idea and discussion.

**Comment by sindresorhus** [comment]
> My preferred solution would be to reverse the order of how you are extending Ky, such that you only ever add headers and never delete them.

I agree. We should definitely document that as the preferred solution. But I still think it makes sense to allow deleting headers.

> That said, I will give this some more thought. Maybe we should support null here, though I know Sindre tweeted somewhat recently about only using undefined. Seems a little awkward to me in this case.

Why is `undefined` any more awkward than `null`?

Alternatively, we could use a `Symbol`:

```js
const http = ky.create({
  headers: {
    authorization: ky.clearHeader,
  }
});
```

Where `ky.clearHeader` is a symbol that indicates to Ky that the header should be cleared. Name is up for discussion.

> Does got have this functionality?

Yes: https://github.com/sindresorhus/got#headers

**Comment by sholladay** [comment]
> Why is `undefined` any more awkward than `null`?

I was thinking that we would have to distinguish between _implicit_ vs _explicit_ `undefined`. But on second thought, that's not really true - we'll loop over the input `headers` and just pay attention to any explicit `undefined` value. It'll be fine. I don't think we need a symbol.

**Comment by sindresorhus** [comment]
Alright, let's go with `undefined` then.

**Comment by szmarczak** [comment]
The same should be for `Got` I think...

**Comment by sindresorhus** [comment]
@szmarczak Yes, indeed.

**Comment by sindresorhus** [comment]
If anyone wants to work on this, see the initial attempt and feedback in https://github.com/sindresorhus/ky/pull/197.
