### ISSUE TITLE
update hooks signatures in readme 

### ISSUE THREAD

**Issue by sky-code** [sindresorhus/ky#213]
example from readme:
```javascript
const api = ky.extend({
	hooks: {
		beforeRequest: [
			request => {
				request.headers.set('X-Requested-With', 'ky');
			}
		]
	}
});
```
is not valid anymore, ky call to hooks with different parameters:
```javascript
const result = await hook(this._input, this._options);
```

**Comment by sholladay** [comment]
You are looking at the readme for the latest version of Ky, but using an old version of Ky in your project. Check the readme that is appropriate for the version you are using.
