### ISSUE TITLE
ReferenceError: 'URLSearchParams' is not defined

### ISSUE THREAD

**Issue by sunknudsen** [sindresorhus/ky#215]
Hi,

Sentry is reporting the following reference error on Edge version 16.

```
ReferenceError: 'URLSearchParams' is not defined
  at param(../node_modules/ky/index.js:331:5)
```

Is something broken at my end of there is an issue with Ky?

Thanks,

Sun

**Comment by sindresorhus** [comment]
From the readme:

> Ky targets modern browsers and Deno. For older browsers, you will need to transpile and use a fetch polyfill.

**Comment by sunknudsen** [comment]
@sindresorhus Edge version `16.16299` was [released](https://en.wikipedia.org/wiki/Microsoft_Edge#EdgeHTML_(2014%E2%80%932019)_2) on September 26, 2017. Is that considered an old browser?

**Comment by sunknudsen** [comment]
https://www.npmjs.com/package/url-search-params-polyfill did the job. Thanks @sindresorhus.

**Comment by sholladay** [comment]
For the record, Edge has `URLSearchParams` and it should work, but only in Edge 17 and newer.

**Comment by sindresorhus** [comment]
(Old) Edge is not considered a modern browser as it doesn't auto-update and it's missing a lot of expected features. Chromium-based Edge, however, is considered a modern browser, but it's not stable yet.
