### ISSUE TITLE
Issue with 1 ms delay before awaiting fetch

### ISSUE THREAD

**Issue by tommarien** [sindresorhus/ky#220]
In pull #118, a 1 ms delay was added i am wondering what was the reasoning behind this, as far as i can see it looks like

```
const parsed = await ky.get('url').json();
```

was the reasoning for it ? its a bit counter intuitive to have 1 ms delay before a fetch ;)

**Comment by sholladay** [comment]
The discussion about this explaining why is right there in the pull request you linked to. See: https://github.com/sindresorhus/ky/pull/118#issuecomment-479620696, https://github.com/sindresorhus/ky/pull/118#issuecomment-480062257, and https://github.com/sindresorhus/ky/pull/118#issuecomment-480186074, etc.

The reason for the teeny tiny delay is effectively to allow the `.json()` method to run _before_ the request is sent by `.get()`, even though `.get()` is actually called first. This is an under the hood implementation detail that users should neither notice nor rely upon.

It might feel a little strange, but consider that any HTTP request is going to take a significant amount of time and will be asynchronous anyway. It should be inconsequential. `got` has been doing something similar for years with no ill effect. Also, if browsers implement something like `setImmediate()`, we should be able to further reduce this delay.

If you have strong feelings about removing it, then propose an API that allows Ky to know the desired response type ahead of time. I like `ky.json.get()`, personally. But Sindre preferred the current API when we discussed it in the comments on that PR. (For some reason, I originally proposed `ky.get.json()` which seems like a mistake in hindsight, it should be the other way around.)

**Comment by tommarien** [comment]
@sholladay I guess it's fine was just wondering why the delay of 1 ms and not just next tick by delaying 0 ms ? or basicly

```
await(async () => {})
```

**Comment by sholladay** [comment]
I am not sure why `1` was chosen over `0`. It may be for clarity, to indicate that it is, in fact, delaying. It's not entirely unreasonable to expect `await delay(0)` to do nothing, even though it will actually cause a delay.

Feel free to submit a PR to change it. If it works and there are no objections, I will merge it.
