### ISSUE TITLE
TypeScript issue with React Native + /// <reference lib="dom"/>

### ISSUE THREAD

**Issue by viggyfresh** [sindresorhus/ky#224]
Hi there! I am consuming this library via [Draqula](https://github.com/vadimdemedes/draqula), and came across a thorny TypeScript issue that I'm struggling to work around.

Basically, the problem is: Draqula uses this library under the hood, and naturally exports some of the underlying `ky` types. This works great in the browser + DOM context. However, when working in React Native, the DOM library reference (`/// <reference lib="dom"/>`) in `index.d.ts`  wreaks havoc, because the DefinitelyTyped React Native types have a bunch of duplicate identifiers (like Request, FormData, etc). Because of that reference, despite my TypeScript compiler settings excluding DOM from the list of provided TypeScript libs, it gets pulled in anyway.

I'm cognizant of the fact that mine is a fringe use case - but is there any way I could convince you to _not_ include that reference at the top of the file? If you need it, you can always provide `libs` via `tsconfig.json` or the command line - but if you don't need it, then there's no way to escape it unless it isn't included as a reference. If there exists an alternative, I'd love to try that out as well. Thanks in advance!

**Comment by sholladay** [comment]
I've always wondered how we should handle conflicting identifiers with common names like `Request`. Seems to me like removing the reference is the way to go.

There is basically a need for something equivalent to a `peerDependency`, leaving the management of such types up to the end user.

**Comment by viggyfresh** [comment]
yeah totally agree - with the edge case here being that `dom` isn't a peer dependency so much as it is a "what environment are you compiling against". full transparency - this will be a breaking change for lots of people. for example, when removed that line, other types that implicitly depended on DOM started complaining about missing identifiers like `DocumentFragment`

**Comment by viggyfresh** [comment]
but, pedantically, those types should have been complaining long ago 😄

**Comment by vadimdemedes** [comment]
Just stumbled upon this one as well, also using Draqula in React Native environment. I've tried just removing the reference, but new errors pop up among others:

```
node_modules/ky/index.d.ts:56:14 - error TS2304: Cannot find name 'URL'.
56  prefixUrl?: URL | string;
                ~~~

node_modules/ky/index.d.ts:120:31 - error TS2304: Cannot find name 'URL'.
120 export type Input = Request | URL | string;
```

I think best (and least hacky for `ky`) course of action here would be to patch `ky` using [patch-package](https://npmjs.com/package/patch-package) by removing `dom` reference and adding missing types to my project's `global.d.ts`.

**Comment by vadimdemedes** [comment]
@viggyfresh I'm going to try fixing it without affecting `ky`, write it up and publish it on Draqula's repo, you can track it here - https://github.com/vadimdemedes/draqula/issues/25.

**Comment by vadimdemedes** [comment]
Published a solution at https://draqulajs.com/docs/recipes.

**Comment by viggyfresh** [comment]
Thanks!

**Comment by sholladay** [comment]
Hey all. What should we do with this issue? I see that Draqula has a relatively simple, albeit unfortunately necessary, solution. But this seems like a more general problem.

I don't think it would be that bad if Ky's TypeScript users had to include `libs: ['dom']` in their `tsconfig.json`. Should we remove the [`<reference>`](https://github.com/sindresorhus/ky/blob/f67304ee71ab2cc675a5590e414c2daf695b337d/index.d.ts#L1) line from `index.d.ts` and document the need for `libs: ['dom']`? Are there any downsides to doing so, other than it being a breaking change? Should we just close this issue and hope TypeScript itself provides some kind of solution in the future?

**Comment by viggyfresh** [comment]
> Hey all. What should we do with this issue? I see that Draqula has a relatively simple, albeit unfortunately necessary, solution. But this seems like a more general problem.
> 
> I don't think it would be that bad if Ky's TypeScript users had to include `libs: ['dom']` in their `tsconfig.json`. Should we remove the [`<reference>`](https://github.com/sindresorhus/ky/blob/f67304ee71ab2cc675a5590e414c2daf695b337d/index.d.ts#L1) line from `index.d.ts` and document the need for `libs: ['dom']`? Are there any downsides to doing so, other than it being a breaking change? Should we just close this issue and hope TypeScript itself provides some kind of solution in the future?

hey @sholladay - I think the technically correct thing to do is to force people to include `libs: ['dom']` (definite breaking change). I don't anticipate TypeScript being able to provide a solution here - at least, not one that can uniformly work across browser + other JS runtimes.
