### ISSUE TITLE
Disable retry

### ISSUE THREAD

**Issue by popuguytheparrot** [sindresorhus/ky#225]
Hi. Is it possible to disable `retry`? How?

**Comment by sindresorhus** [comment]
Set `retry` to `0`.

**Comment by josh08h** [comment]
Is that true @sindresorhus ?

[It looks as though](https://github.com/sindresorhus/ky/blob/d547e89fba92b13333f5b714bf79fb59b4690253/index.js#L302) retry is always invoked & doesn't take `retry` into account?

**Comment by sindresorhus** [comment]
We have a test for that: https://github.com/sindresorhus/ky/blob/7be6d00abde87879ab0ce1c5316ad5d75866102b/test/retry.js#L389-L412 If there's somthing we have overlooked, it would be great if you could submit a test proving it and we'll fix asap.

**Comment by sholladay** [comment]
See the checks in `_retry` and `_calculateRetryDelay` as they are responsible for this behavior.
