### ISSUE TITLE
Retries for POST still broken

### ISSUE THREAD

**Issue by veeralpatel** [sindresorhus/ky#234]
I'm noticing that retries for POST requests is still broken. I have the following options set, yet my request is never retried:
`    timeout: 500,
      retry: {
        limit: 3,
        methods: ["post"],
        statusCodes: [400, 401, 500, 504]
      }
`

#230

**Comment by sholladay** [comment]
You should verify that you are actually using v0.17. It'll need to be explicitly updated in your package.json or import URL and then delete and reinstall your `node_modules`, if applicable, and potentially also clear your browser cache.

Assuming none of that works, it would be useful if you could submitted either a failing test or a reproducible example on CodeSandbox or similar.

**Comment by sholladay** [comment]
@DanielRuf are you still having issues with retrying `POST` requests, using v0.17? Looking for anyone who can provide an example. I haven't been able to reproduce this. v0.17 fixed all known bugs with retries, as far as I am aware (excluding #233, which is more of a Chromium bug that we might want to work around).

**Comment by DanielRuf** [comment]
I can not say as we did not migrate back from GET requests as the application has to work in production right now. Not really time to test this now.

**Comment by DanielRuf** [comment]
But I guess I was mentioned by accident as I was not involved with this issue here until today.

**Comment by sholladay** [comment]
No, not an accident, Daniel. This issue is claiming that your issue, #230, is not actually fixed in Ky v0.17.

However, I tend to disagree, given the evidence I have at hand. I was hoping you could weigh in. But it's okay if you don't have time.

I'm going to close this. Will reopen if new evidence comes to light.
