### ISSUE TITLE
Cannot read property 'clone' of undefined

### ISSUE THREAD

**Issue by Filatov-Nikita** [sindresorhus/ky#245]
```js
import ky from 'ky';


const api = ky.create({
  prefixUrl: 'https://crm.some.com/api/',
  retry: {
      statusCodes: [408, 413, 429],
      limit: 4
  },
  hooks: {
    beforeRequest: [
      request => {
        const token = localStorage.getItem('accessToken');

        if(token !== null) {
          request.headers.set('Authorization', 'Bearer ' + token)
        }
      }
    ],
    afterResponse: [
      async (request, options, response) => {
        const refresh_token = localStorage.getItem('refreshToken');

        if(response.status === 401) {
          let tokensData = await api.post('b2b/auth/token', {
            json: {
              "client_id": "1",
              "client_secret": "YjloNVdrdmd4X4gccxuErHUrt8fjRAhcWrRyHwu6",
              "grant_type": "refresh_token",
              refresh_token,
              "scope": ""
            }
          }).json();

          localStorage.setItem('accessToken', tokensData.access_token);
          localStorage.setItem('refreshToken', tokensData.refresh_token);

          request.headers.set('Authorization', 'Bearer ' + token);

          console.log(request, options);

          return ky(request);
        }


      }
    ],
    beforeRetry: [
      response => {
        console.log(response);
        return response
      }
    ],
  }
});

export {api};
```

```
TypeError: Cannot read property 'clone' of undefined
    at Ky._retry (index.js?d823:366)
    at async Promise.Ky.result.<computed> [as json] (index.js?d823:307)
```

The bug appears to be `request.headers.set('Authorization', 'Bearer ' + token);`

If I remove the `beforeRetry` hook the bug disappears.

I think that the request must not change in a `afterResponse` hook, but why is this bug disappearing when I remove that hook?

**Comment by szmarczak** [comment]
The `afterResponse` hook accepts a Response, not a Promise.

**Comment by Filatov-Nikita** [comment]
> The `afterResponse` hook accepts a Response, not a Promise.

I take it from doc example 

Why can’t I do the same?

`import ky from 'ky';

(async () => {
	await ky('https://example.com', {
		hooks: {
			afterResponse: [
				(_request, _options, response) => {
					// You could do something with the response, for example, logging.
					log(response);

					// Or return a `Response` instance to overwrite the response.
					return new Response('A different response', {status: 200});
				},

				// Or retry with a fresh token on a 403 error
				async (request, options, response) => {
					if (response.status === 403) {
						// Get a fresh token
						const token = await ky('https://example.com/token').text();

						// Retry with the token
						request.headers.set('Authorization', `token ${token}`);

						return ky(request);
					}
				}
			]
		}
	});
})();`

**Comment by szmarczak** [comment]
You do not return the response from that `afterResponse` hook. This:

```js
    afterResponse: [
      async (request, options, response) => {
        const refresh_token = localStorage.getItem('refreshToken');

        if(response.status === 401) {
          let tokensData = await api.post('b2b/auth/token', {
            json: {
              "client_id": "1",
              "client_secret": "YjloNVdrdmd4X4gccxuErHUrt8fjRAhcWrRyHwu6",
              "grant_type": "refresh_token",
              refresh_token,
              "scope": ""
            }
          }).json();

          localStorage.setItem('accessToken', tokensData.access_token);
          localStorage.setItem('refreshToken', tokensData.refresh_token);

          request.headers.set('Authorization', 'Bearer ' + token);

          console.log(request, options);

          return ky(request);
        }


      }
    ],
```

is the same as:

```diff
    afterResponse: [
      async (request, options, response) => {
        const refresh_token = localStorage.getItem('refreshToken');

        if(response.status === 401) {
          let tokensData = await api.post('b2b/auth/token', {
            json: {
              "client_id": "1",
              "client_secret": "YjloNVdrdmd4X4gccxuErHUrt8fjRAhcWrRyHwu6",
              "grant_type": "refresh_token",
              refresh_token,
              "scope": ""
            }
          }).json();

          localStorage.setItem('accessToken', tokensData.access_token);
          localStorage.setItem('refreshToken', tokensData.refresh_token);

          request.headers.set('Authorization', 'Bearer ' + token);

          console.log(request, options);

          return ky(request);
        }

+		return undefined;
      }
    ],
```

So you need to `return response;` after the `if` clause.

**Comment by Filatov-Nikita** [comment]
> You do not return the response from that `afterResponse` hook. This:
> 
> ```js
>     afterResponse: [
>       async (request, options, response) => {
>         const refresh_token = localStorage.getItem('refreshToken');
> 
>         if(response.status === 401) {
>           let tokensData = await api.post('b2b/auth/token', {
>             json: {
>               "client_id": "1",
>               "client_secret": "YjloNVdrdmd4X4gccxuErHUrt8fjRAhcWrRyHwu6",
>               "grant_type": "refresh_token",
>               refresh_token,
>               "scope": ""
>             }
>           }).json();
> 
>           localStorage.setItem('accessToken', tokensData.access_token);
>           localStorage.setItem('refreshToken', tokensData.refresh_token);
> 
>           request.headers.set('Authorization', 'Bearer ' + token);
> 
>           console.log(request, options);
> 
>           return ky(request);
>         }
> 
> 
>       }
>     ],
> ```
> 
> is the same as:
> 
> ```diff
>     afterResponse: [
>       async (request, options, response) => {
>         const refresh_token = localStorage.getItem('refreshToken');
> 
>         if(response.status === 401) {
>           let tokensData = await api.post('b2b/auth/token', {
>             json: {
>               "client_id": "1",
>               "client_secret": "YjloNVdrdmd4X4gccxuErHUrt8fjRAhcWrRyHwu6",
>               "grant_type": "refresh_token",
>               refresh_token,
>               "scope": ""
>             }
>           }).json();
> 
>           localStorage.setItem('accessToken', tokensData.access_token);
>           localStorage.setItem('refreshToken', tokensData.refresh_token);
> 
>           request.headers.set('Authorization', 'Bearer ' + token);
> 
>           console.log(request, options);
> 
>           return ky(request);
>         }
> 
> +		return undefined;
>       }
>     ],
> ```
> 
> So you need to `return response;` after the `if` clause.

Great! I found a reason of this bag. 

Actually, I make mistake in this place `request.headers.set('Authorization', 'Bearer ' + token)`

I am trying perform addition string and nonexistent variable 

So This mistake display as
`TypeError: Cannot read property 'clone' of undefined
    at Ky._retry (index.js?d823:366)
    at async Promise.Ky.result.<computed> [as json] (index.js?d823:307)`

Why? I don't know, but I think this mistake call a `beforeRetry` hook and there is an error above
