### ISSUE TITLE
An undefined HTTPError message breaks New Relic

### ISSUE THREAD

**Issue by kumar303** [sindresorhus/ky#248]
An app I work on uses [New Relic browser monitoring](https://newrelic.com/products/browser-monitoring) for errors and in the case where `ky` throws an `HTTPError` with an undefined message, New Relic breaks like this:

<img width="348" alt="Screen Shot 2020-04-08 at 10 49 59 AM" src="https://user-images.githubusercontent.com/55398/78824816-946d2600-79a4-11ea-9ea4-2f2701db1493.png">

The top line shows 215 `ky` `HTTPError` instances but you can't see what they are and you can't click on them. I used the stack traces to confirm they are `ky.HTTPError()` instances. 

This is most certainly a New Relic bug but I think it would be nice if `ky` always defined an `HTTPError` message.

Why would an `HTTPError` message be undefined? I couldn't reproduce it exactly but I think it's because browsers like Safari, IE, and others do not define [`response.statusText`](https://developer.mozilla.org/en-US/docs/Web/API/Response/statusText#Browser_compatibility).

**Comment by kumar303** [comment]
I proposed a patch which should fix it: https://github.com/sindresorhus/ky/pull/249

**Comment by sholladay** [comment]
Could some of these requests be using HTTP/2?

Look how much of a mess this is...
https://github.com/whatwg/fetch/issues/599

**Comment by kumar303** [comment]
Ah, possibly. In my error metrics I see that they are coming from recent browser versions (Safari, Chrome). I still cannot reproduce them myself when using the same browser versions, though.
