### ISSUE TITLE
naming

### ISSUE THREAD

**Issue by vitordino** [sindresorhus/ky#25]
I know this was probably on purpose, or at least less important than the [reasons pointed on the readme](https://github.com/sindresorhus/ky#what-does-ky-mean). however I have a really hard time dissociating this from the [homonymous product](https://en.wikipedia.org/wiki/K-Y_Jelly) 🤔. 

of course this could be a plus on describing the lib — like "less friction on your client HTTP requests" — and it's always nice to have a short `npm` name.

on future releases we may mirror it to another name if it's commonly agreed between maintainers here.. (hey, `bhr` for _browser http request_ is still available 😅)

**Comment by eliseumds** [comment]
Wow, great suggestion with "less friction" haha
