### ISSUE TITLE
TypeError o.response is undefined

### ISSUE THREAD

**Issue by lambdalisue** [sindresorhus/ky#251]
The `error.response` on https://github.com/sindresorhus/ky/blob/master/index.js#L374
is `undefined` when the error is `AbortError`.

![ky](https://user-images.githubusercontent.com/546312/80375918-ffd75300-88d3-11ea-9761-7150d0a4b3db.png)

Should I catch that exception in the retry function?

**Comment by lambdalisue** [comment]
I'm sorry. I could not reproduce this error on Google Chrome / Safari thus might be my Firefox is broken.

**Comment by sholladay** [comment]
This looks like a legit bug in Ky, unfortunately. The error may not have a response on it, which we don't check before attempting to clone it.

In hindsight, I'm kind of regretting https://github.com/sindresorhus/ky/pull/201. People should almost certainly just use `error.response`. This shortcut provides very little value.
