### ISSUE TITLE
Support custom JSON parser

### ISSUE THREAD

**Issue by kirillgroshkov** [sindresorhus/ky#254]
In our codebase (that we're migrating to ky) we use a "JSON reviver" (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse), which works like this:

```typescript
const parsed = JSON.parse(myJson, myReviver)
```

I don't see that ky supports it.

I did a workaround (that looks ugly) now via afterResponseHook:

```typescript
const afterResponseHook: AfterResponseHook = async (_req, _opt, res) => {
  if (!res.ok) return   
  // Parse with JSON Reviver (if possible)   
  const data = JSON.parse(await res.text(), backendResponseReviver)

  // Weird, but pack the "revived" json object back to string, so it can be parsed without reviver then :)
  return new Response(JSON.stringify(data, backendResponseReviver), res)
}
```

Nicer API would be (for example; not certain about the naming of `json()` options):
```typescript
const response = await ky.get(url).json({ reviver: myReviver })
```

What do you think?

I can try to submit a PR if you think it's a feasible approach.

**Comment by sholladay** [comment]
I think I'm slightly against having a `reviver` option, as it's kind of a niche use case and it _is_ possible to accomplish your end goal with a hook already, as you demonstrated. Maybe we could generalize this a bit and have a `parseJson` function option. That way you could use a reviver, but you could also use an alternative parsing implementation, such as [bourne](https://github.com/hapijs/bourne), which useful in some cases.

**Comment by kirillgroshkov** [comment]
Agree that `bourne` is a good use-case.

With my hook implementation there's one discrepancy though that broke our code in one place. "json-wise" the result is the same, but we had a reviver that constructs a certain class (called `Price` in our case) and we had a code that tests for `a instanceof Price` that failed now (if reviver wasn't used). We'll change the code (in this specific case), but still a limitation.

Agree that reviver is a niche-case (I'd prefer us not to have them, but it's out of control at the moment).

So, `parseJson` option should solve all cases I believe!

**Comment by kirillgroshkov** [comment]
Off topic here, but same `parseJson` option would be nice to have in `got` for same reasons (bourne/revivers). If you agree - I can open issue in `got` too

**Comment by sindresorhus** [comment]
I'm ok with a `parseJson` option. The docs should mention the two use-cases for it mentioned here.

**Comment by sindresorhus** [comment]
> Off topic here, but same parseJson option would be nice to have in got for same reasons (bourne/revivers). If you agree - I can open issue in got too

👍

**Comment by kirillgroshkov** [comment]
I'll try to do the PR now!

**Comment by kirillgroshkov** [comment]
@sholladay @sindresorhus please kindly look at my PR https://github.com/sindresorhus/ky/pull/257
