### ISSUE TITLE
Creating a client with headers throws an exception if isomorphic-fetch was required before

### ISSUE THREAD

**Issue by TPXP** [sindresorhus/ky#258]
Hello, thanks for this project. I noticed the following code does not work (while being in readme), when running the module with Node.JS. I was able to reproduce it with `ky-universal` as well

```js
const ky = require('ky-universal'); // or ky/umd

const myClient = ky.create({
  prefixUrl: "http://example.org",
  headers:{
    ['Api-Token']: "testtest",
  }
});
```

Environment:
* NodeJS v14.3.0 with `ky` (works with ky-universal)
```
Uncaught TypeError: globals.Headers is not a constructor
    at mergeHeaders (/app/node_modules/ky/umd.js:61:18)
    at deepMerge (/app/node_modules/ky/umd.js:97:16)
    at validateAndMerge (/app/node_modules/ky/umd.js:493:10)
    at Function.ky.create (/app/node_modules/ky/umd.js:505:45)
```
On NodeJS v12, the error is different (same with `ky` and `ky-universal`):
```
serverless_1     | TypeError: source is not iterable
serverless_1     |     at mergeHeaders (/app/node_modules/ky/umd.js:62:30)
serverless_1     |     at deepMerge (/app/node_modules/ky/umd.js:94:16)
serverless_1     |     at validateAndMerge (/app/node_modules/ky/umd.js:490:10)
serverless_1     |     at Function.ky.create (/app/node_modules/ky/umd.js:502:45)
serverless_1     |     at Object.<anonymous> (/app/activecampaign.js:17:21)
serverless_1     |     at Module._compile (internal/modules/cjs/loader.js:956:30)
serverless_1     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
serverless_1     |     at Module.load (internal/modules/cjs/loader.js:812:32)
serverless_1     |     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
serverless_1     |     at Module.require (internal/modules/cjs/loader.js:849:19)
serverless_1     |     at require (internal/modules/cjs/helpers.js:74:18)
serverless_1     |     at /app/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js:71:68
serverless_1     |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
serverless_1     |     at InProcessRunner.run (/app/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js:71:9)
```

**Comment by sholladay** [comment]
Ky is mainly meant for browsers, but can be used in Node under certain circumstances, so long as certain APIs are polyfilled, including the [`Headers`](https://developer.mozilla.org/en-US/docs/Web/API/Headers) class in this case, as Node does not have `Headers` out of the box. `ky-universal` is a variant of Ky that includes the necessary polyfills so everything "just works" regardless of your environment.

`ky-universal` polyfills the `Headers` class here: https://github.com/sindresorhus/ky-universal/blob/3eca77b01a3b4139a95bfe3567406ca83d7f5485/index.js#L11-L13

I think there are really two separate issues you encountered.

1. > TypeError: globals.Headers is not a constructor

    This one is because you used Ky in Node **and** used a feature (`headers`) that Ky is unable to support in Node due to missing APIs in the environment. Use `ky-universal` instead.

2. > TypeError: source is not iterable

    This one sounds like it _could_ be a bug. However, I am not able to reproduce it and I'm not sure what would cause it. We have an extensive suite of [headers tests](https://github.com/sindresorhus/ky/blob/master/test/headers.js) that are passing. The error is referring to [this line](https://github.com/sindresorhus/ky/blob/2c5d6dda8ac889048408a337c3f5d068769981b2/index.js#L56). Needs more investigation. Can you double check the code that you used and also tell me the version of Ky and `ky-universal` that this error happens with?

**Comment by TPXP** [comment]
Thanks for your quick reply! :+1: 

Apologies for the mess up with `ky` and `ky-universal`, it's definitely mentioned in the README. Perhaps add a warning on import, to give a clearer hint?

I tried my code on Linux and it seems to work, while I'm pretty sure I had these errors on MacOS (but I'm running this in docker, which relies on a Linux VM?). I'll definitely check this twice and get back to you, promised! (pun intended)

**Comment by TPXP** [comment]
OK, got it!

As you probably guessed from my error logs, I was using `serverless-offline` in my development environment, which simply `require`s modules by default, thus passing them the global environment of the serverless profile. Turns out serverless relies somehow on [`isomorphic-fetch`](https://github.com/matthew-andrews/isomorphic-fetch), which gets `require`d at some point, and will set `global.Headers` [among others](https://github.com/matthew-andrews/isomorphic-fetch/blob/master/fetch-npm-node.js).

It relies on `node-fetch`, which seems to define an iterator on the `Headers` object though. I noticed ky-universal also seems to rely on node-fetch, I'm guessing there is a conflict there?

Here is an easy-to-reproduce example:
```sh
npm add --save ky ky-universal isomorphic-fetch
cat <<EOF > index.js
require('isomorphic-fetch');
const ky = require('ky-universal');
ky.create({
  headers:{yolo:"yay"}
});
EOF
node index.js
```

**Comment by sholladay** [comment]
I looked into this and it appears that `node-fetch` is the source of the bug.

Here is a minimal reproduction which throws the same error you described, even though it ought to work:

```js
const nf = require('node-fetch');

const headers = new nf.Headers();

for (const header of headers) {
    console.log('header:', header);
}
```

Throws: `TypeError: headers is not iterable`

And the error makes sense as `node-fetch` doesn't implement an iterator on `Headers`.

```js
const nf = require('node-fetch');
console.log(nf.Headers.prototype[Symbol.iterator]);
// undefined
```

Unfortunately, there is nothing we can do about this in Ky itself. It'll have to be implemented in `node-fetch`. I suggest filing an issue over there and then commenting here with a link to the issue, in case other people run into this.

**Comment by TPXP** [comment]
Thank you for looking into this, I'll try that

**Comment by TPXP** [comment]
So, it seems node-fetch already implements iterable headers since https://github.com/node-fetch/node-fetch/pull/180... But since node-fetch has not been updated in 5 years, it still has the old version without this method. PRs were opened though, like https://github.com/matthew-andrews/isomorphic-fetch/pull/180.

Nothing much we can do, I guess. But at least I've learned about `Symbol.iterator` today!

**Comment by sholladay** [comment]
The last publish of `node-fetch` on npm was only a month ago. It seems like it should work, based on what I see at a glance from the source code. But for some reason the iterator isn't actually there when I access it using the release.

**Comment by TPXP** [comment]
Oh, my bad, I meant `isomorphic-fetch`. Apologies for the confusion 😅
