### ISSUE TITLE
consider export Ky class?

### ISSUE THREAD

**Issue by zhuangya** [sindresorhus/ky#26]
if export the class Ky, others can write their own client with just `extend Ky`

**Comment by sindresorhus** [comment]
That would be a fragile and leaky abstraction. The class is just used internally to make it easier to create the aliases and extend method. I think [composition is a better approach than inheritance](https://www.google.co.th/search?q=composition+over+inheritance&oq=composition+over+in&aqs=chrome.0.0j69i57j0l4.3624j1j1&sourceid=chrome&ie=UTF-8). We'll probably end up doing something like the [`.create()`](https://github.com/sindresorhus/got/blob/master/advanced-creation.md#gotcreatesettings) method in Got eventually instead.
