### ISSUE TITLE
Edge <= 18 Invalid argument exception

### ISSUE THREAD

**Issue by JosNun** [sindresorhus/ky#260]
Pre-Chromium Microsoft Edge blows up when `undefined` is passed as an argument to the `window.Headers` constructor. As such, ky blows up when trying to make a request due to [these lines](https://github.com/sindresorhus/ky/blob/2c5d6dda8ac889048408a337c3f5d068769981b2/index.js#L52).

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ky#browser-support

**Comment by JosNun** [comment]
Thanks for the quick response. Would you be open to a pull request to patch it for Edge?

**Comment by sholladay** [comment]
Does it work if you pass `null`? Personally, I'm fine with adding a simple ternary. But yeah, earlier versions of Edge may have other problems too, as they are unsupported.

**Comment by JosNun** [comment]
Nope, it blows up with `null` the same as it does with `undefined`. Chromium and Firefox blow up with `null` as well (they work fine when passed `undefined`, however).

**Comment by JosNun** [comment]
Fwiw, we used `patch-package` and added a nullish coalescing operator to handle the `undefined` case and it's been working so far. Though, we aren't using any of the more advanced features.
```js
// we changed this
const result = new globals.Headers(source1);
// to this
const result = new globals.Headers(source1 ?? {});
```
Though, to provide better support when using it without transpiling, I believe a simple `||` would work as well.

**Comment by myh110** [comment]
Chrome version 49 has the same problem

**Comment by belgattitude** [comment]
This hit us the hard way...

**Comment by JosNun** [comment]
@belgattitude if you need a quick fix till there's a release with this fix in it, we've had good luck using `patch-package` since it's such a small change.

**Comment by belgattitude** [comment]
Thanks ! I did a separate release (https://github.com/sindresorhus/ky/pull/264#issuecomment-652431596)... But good to know about patch-package I'll use it for sure
