### ISSUE TITLE
ky does not work with create-react-app

### ISSUE THREAD

**Issue by andrewbihl** [sindresorhus/ky#280]
Steps to reproduce:

1. `npx create-react-app app --typescript`
2. `yarn add ky`

3. Add file src/fetch-a-thing.ts:

```
import ky from 'ky'

export function fetchSomething() {
    ky.get('http://google.com')
    return true
}
```

4. Add file src/fetch-a-thing.test.ts:

```
import {fetchSomething} from './fetch-a-thing'

test('fetchSomething', () => {
    const res = fetchSomething()
    expect(res).toEqual(true)
})
```

Run: `yarn test`.

Output:

```
 FAIL  src/fetch-a-thing.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/andrew.bihl/velocity/app/node_modules/ky/index.js:523
    export default createInstance();
    ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import ky from 'ky'
        | ^
      2 | 
      3 | export function fetchSomething() {
      4 |     ky.get('http://google.com')

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (src/fetch-a-thing.ts:1:1)
```

----
I've broken this down into the simplest possible version. Running just these steps and nothing else causes the issue, even though all of the involved technologies (typescript, jest, react, create-react-app) claim to support the others.

**Comment by sindresorhus** [comment]
This sounds like a configuration issue with Jest. Ky is working fine both in tests here and production for many users.

https://jestjs.io/en/help

**Comment by manavm1990** [comment]
> Steps to reproduce:
> 
>     1. `npx create-react-app app --typescript`
> 
>     2. `yarn add ky`
> 
>     3. Add file src/fetch-a-thing.ts:
> 
> 
> ```
> import ky from 'ky'
> 
> export function fetchSomething() {
>     ky.get('http://google.com')
>     return true
> }
> ```
> 
>     4. Add file src/fetch-a-thing.test.ts:
> 
> 
> ```
> import {fetchSomething} from './fetch-a-thing'
> 
> test('fetchSomething', () => {
>     const res = fetchSomething()
>     expect(res).toEqual(true)
> })
> ```
> 
> Run: `yarn test`.
> 
> Output:
> 
> ```
>  FAIL  src/fetch-a-thing.test.ts
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     /..../ky/index.js:523
>     export default createInstance();
>     ^^^^^^
> 
>     SyntaxError: Unexpected token 'export'
> 
>     > 1 | import ky from 'ky'
>         | ^
>       2 | 
>       3 | export function fetchSomething() {
>       4 |     ky.get('http://google.com')
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
>       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
>       at Object.<anonymous> (src/fetch-a-thing.ts:1:1)
> ```
> 
> I've broken this down into the simplest possible version. Running just these steps and nothing else causes the issue, even though all of the involved technologies (typescript, jest, react, create-react-app) claim to support the others.

It definitely seems like `jest`. I was encountering this very similar issue and had to bring in Babel to properly transpile. LMK, and I can link to my setup repo. @andrewbihl

**Comment by sholladay** [comment]
See their experimental support for ES modules:
https://jestjs.io/docs/ecmascript-modules
