### ISSUE TITLE
Include request object in HTTPError

### ISSUE THREAD

**Issue by ialexi-bl** [sindresorhus/ky#287]
I would suggest attaching request object to `HTTPError`. It would be useful to log request body, credentials policy etc. For now I have to use a custom http error, which leads to some problems with retry logic, so now I have to write a `beforeRetry` hook that checks whether request should be retried or not. It doesn't seem to do any damage to include request in `HTTPError`, so why not to do it? Also you could include `options` as well, because after normalization they could be used for logging as well

**Comment by sholladay** [comment]
I'm fine with this. Though, the hooks already receive the request and response, so in many cases it wouldn't make a difference. But it is a nice convenience to have those the error.

**Comment by ialexi-bl** [comment]
@sholladay, hooks receive request, but errors aren't always handled in hooks. Maybe some particular part of an application may want to log one request that failed unexpectedly, or in React apps error may get to error boundary which wants to log it, but can't do it, because it doesn't know the details of the request, so that would be helpful
