### ISSUE TITLE
Add `afterResponse` hook

### ISSUE THREAD

**Issue by nnals** [sindresorhus/ky#29]
hello,

are there any plans to add a afterResponse hook like [axios' response interceptor](https://github.com/axios/axios/blob/master/README.md#interceptors)?

thank you for this library!
nicolai

**Comment by sindresorhus** [comment]
Can you share some use-cases for this?

**Comment by sindresorhus** [comment]
PR welcome :)

**Comment by robjtede** [comment]
- Automatic logging for `HTTPError`s.
- Similarly, redirecting if the error code is 401 Unauthorized.
- Response sanitization / escaping

Just a couple use cases that came to mind

**Comment by sarneeh** [comment]
Just came here to propose the same feature. I'd love to see that to be able to **refresh access tokens on 401 responses.**
