### ISSUE TITLE
Broken ky.stop

### ISSUE THREAD

**Issue by ialexi-bl** [sindresorhus/ky#290]
This line causes causes `TypeError: cannot read property "clone" of undefined`, when returning `ky.stop` from `beforeRetry` hook

https://github.com/sindresorhus/ky/blob/764bc1cdabdb65bbcd9830b0f8bfbd95fed3179a/index.js#L344

Possible solution would be to throw error here instead of returning nothing, but I'm not sure if this is how it's supposed to work:

https://github.com/sindresorhus/ky/blob/764bc1cdabdb65bbcd9830b0f8bfbd95fed3179a/index.js#L429

**Comment by sholladay** [comment]
Please provide reproducible sample code.

**Comment by ialexi-bl** [comment]
@sholladay, I didn't mention that this happens when using `.json`, but it's still an issue, here is the simplest [example](https://codesandbox.io/s/nifty-firefly-9r3hm?file=/src/index.js:22-244)

```ts
ky
  .put("https://httpstat.us/500/cors", {
    hooks: { beforeRetry: [() => ky.stop] }
  })
  .json()
```

**Comment by ialexi-bl** [comment]
@sholladay , I would submit a pull request, the easiest solution would be to throw the error when `ky.stop` is returned, but is this intended? I don't think it's a nice solution to just return nothing, considering this code:

```ts
ky
  .put("https://httpstat.us/500/cors", {
    hooks: { beforeRetry: [() => ky.stop] }
  })
  .json()
  .then((body) => {
    console.log(body.property)
  })
```

It would be unintuitive that `body` can just be `undefined`. It would be pretty logical that in such case there is an error thrown, but which one? The error that caused the retry attempt? Something else? Maybe using `ky.stop` is not a good idea in the first place and it would be better to instead make some `RetryFailed` error or get rid of it at all and ask users to throw their own errors in order to prevent retrying?

**Comment by sholladay** [comment]
I would expect that code to behave the same as if retries were disabled. And given that the response is a 500 and you haven't disabled throwing of HTTP errors, I would expect it to throw the 500 error.
