### ISSUE TITLE
Stream API

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/ky#3]

**Comment by szmarczak** [comment]
What about `.stream()`?

**Comment by sindresorhus** [comment]
👍 I like it.

**Comment by dangdennis** [comment]
I'd like to work on this. Already have been but it's slower going. I wouldn't mind if anyone else is working on it concurrently for some collaboration/merging of ideas as well.

Do you have any other features to add on besides the built-in `readableStream` and `writableStream`?

**Comment by poppinlp** [comment]
Hi. How's it going? If you don't mind, i'll make a PR this weekend.

**Comment by jdalrymple** [comment]
@sindresorhus was the streaming API ever exposed?

**Comment by sholladay** [comment]
@jdalrymple yes, we added the ability to pass a callback function that receives chunks and metadata about the download progress, which you can use for streaming purposes.

https://github.com/sindresorhus/ky#ondownloadprogress

In the future, we will likely also add the ability to get a `ReadableStream` for the response, as that is already built into `fetch()`.

**Comment by jdalrymple** [comment]
Ah! That's what I was looking for. So the response is currently *not* available to be returned as a readable stream.
