### ISSUE TITLE
Deno and TypeScript "Property 'get' does not exist on type"

### ISSUE THREAD

**Issue by sabifa** [sindresorhus/ky#302]
Hey all!

I'm currently running into an issue with Ky using Deno and TS. 
The full error says:

```
Property 'get' does not exist on type '{ (input: any, options: any): Ky; HTTPError: typeof HTTPError; TimeoutError: typeof TimeoutError; create(newDefaults: any): ...; extend(newDefaults: any): ...; stop: unique symbol; }'.ts(2339)
```

![image](https://user-images.githubusercontent.com/25851344/100464810-8bb19780-30ce-11eb-93c2-239828068d97.png)

This happens with every method (such as post, delete etc).
If I change the file ending to .js so that there is no type checking everything works as expected. Did I misconfigure something or is this an issue related to the package?

Code to reproduce:
```ts
import ky from 'https://unpkg.com/ky/index.js';

const parsed = await ky
  .get("https://jsonplaceholder.typicode.com/todos")
  .json();

console.log(parsed);
```

**Comment by sindresorhus** [comment]
Is this still an issue with the latest Ky version? Ky is now a pure ESM module.

**Comment by awprice** [comment]
Using Deno 1.6.0 and the latest Ky version, the issue seems to be fixed:

```
$ cat test.js 
import ky from 'https://unpkg.com/ky/index.js';

const parsed = await ky
  .get("https://jsonplaceholder.typicode.com/todos")
  .json();

console.log(parsed);
```

```
$ deno --version
deno 1.6.0 (release, x86_64-apple-darwin)
v8 8.8.278.2
typescript 4.1.2
```

```
$ deno run --allow-net test.js 
[
  { userId: 1, id: 1, title: "delectus aut autem", completed: false },
  { userId: 1, id: 2, title: "quis ut nam facilis et officia qui", completed: false },

--- snipped ---
```

**Comment by sholladay** [comment]
@awprice you cannot use a `.js` file to test a TypeScript related issue.

I can confirm it is still happening.

```sh
❯ deno --version
deno 1.6.3 (release, x86_64-apple-darwin)
v8 8.8.294
typescript 4.1.3
❯ deno run main.ts
Check file:///private/tmp/foo/main.ts
error: TS2339 [ERROR]: Property 'get' does not exist on type '{ (input: any, options: any): Ky; HTTPError: typeof HTTPError; TimeoutError: typeof TimeoutError; create(newDefaults: any): ...; extend(newDefaults: any): ...; stop: unique symbol; }'.
  .get("https://jsonplaceholder.typicode.com/todos")
   ~~~
    at file:///private/tmp/foo/main.ts:4:4
```

I don't know enough to say what's happening here, but it feels like a Deno or TypeScript bug to me, because while `ky.get()` does not work, `ky.create()` _does_ work, even though they are both defined in the same way on the same namespace ([here](https://github.com/sindresorhus/ky/blob/bf175f012715fc72736d006933954111615309b1/index.d.ts#L442-L445) and [here](https://github.com/sindresorhus/ky/blob/bf175f012715fc72736d006933954111615309b1/index.d.ts#L487-L492)).

**Comment by sholladay** [comment]
I have a workaround. The Skypack CDN, which points to the TypeScript types via a non-standard header, seems to work. Not exactly ideal to tell people they have to use a specific CDN that does some black magic, but here you go...

```
import ky from 'https://cdn.skypack.dev/ky?dts';
```

**Comment by kidonng** [comment]
I know this issue is closed, but I want to inform [the official way](https://deno.land/manual@v1.8.1/typescript/types#providing-types-when-importing) to provide types for `.js` files, in case you want to use another CDN (in this example jsDelivr):

```ts
// @deno-types="https://cdn.jsdelivr.net/npm/ky/index.d.ts"
import ky from 'https://cdn.jsdelivr.net/npm/ky/index.js'
```
