### ISSUE TITLE
ReferenceError: Property 'Reflect' doesn't exist on ReactNative Android

### ISSUE THREAD

**Issue by ShivamJoker** [sindresorhus/ky#303]
Versions
"ky": 0.25,
"react-native": "0.63.4"

Works fine on iOS

```js
/** Handle the otp generation on forgotPassword */
export const sendOTP = async (email) => {
  try {
    const res = await ky
      .post(`${userAPIURL}/users/forgotPassword`, {
        json: {email: email},
      })
      .json();
    return {success: true, message: 'OTP sent to email'};
  } catch (error) {
    console.log(error);
    const errMsg = await error.response.json();

    // console.log(errMsg);
    return {success: false, message: errMsg.description};
  }
};
```

**Comment by ComputerWolf** [comment]
If you have hermes enabled in react native it does not support Reflect.

You will need to polyfill `Reflect.has` which is the method that ky uses. 

I did this using core-js by including `import 'core-js/es/reflect/has';` as the first line in my entry file.

**Comment by szmarczak** [comment]
The very first paragraph of Ky:

> Ky targets modern browsers and Deno.

**Comment by sholladay** [comment]
Personally, I prefer using the `in` operator instead of `Reflect.has()`, anyway. I'm fine with changing it if the rest of the team is, too.

**Comment by szmarczak** [comment]
I'm +1

**Comment by sindresorhus** [comment]
Sure
