### ISSUE TITLE
Improve project discovery

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [sindresorhus/ky#311]
Hello!

When searching for `js http client fetch` in GitHub, 32 projects are found and none is `ky`. When searching for `http client fetch` 220 projects are found and, luckily, ky is rated as best match and it is the first in the list.

Since GitHub is not only for JS, I think it is natural to type `js` when searching for a js lib, even tho there are dedicated language filters after you run the first search.

Would be possible to improve the search result for this project to match a `js` keyword?

**Comment by sholladay** [comment]
What's your proposed solution? Add `js` to the Topics list? GitHub does automatically analyze repositories and categorizes them by language. You just need to make use of the language feature in the search. It feels a little redundant to add the language to the Topics list. Maybe it's something GitHub should do automatically.

**Comment by rafaelrenanpacheco** [comment]
I think the JS in the topic list or in the project description could work. I understand the language feature in the search can solve this issue, but that requires 2 steps to find ky.

The about could be something like this:

```
Tiny & elegant JS HTTP client based on window.fetch
```

or

```
Tiny & elegant JS HTTP client based on fetch API
```

**Comment by sindresorhus** [comment]
The correct solution is to use `language:javascript` when you search for something. GitHub search is also not very good in general. I would recommend sending feedback to GitHub about that. ke

I have updated the repo description to `🌳 Tiny & elegant JavaScript HTTP client based on the browser Fetch API` and added some repo topics (although I honestly think that should have been unnecessary).
