### ISSUE TITLE
[Feature request] Typing JSON response using TS generics

### ISSUE THREAD

**Issue by nielsdB97** [sindresorhus/ky#312]
I'm considering a move from `axios` to `ky` in order to leverage the Fetch API, which seems to be relatively easy because of the clear APIs and documentation for them in ky. 🙂 
However I'm running into a limitation of the types, where I would like to be able to pass a generic for the Response type.

This is currently [possible in Axios](https://github.com/axios/axios/blob/59ab559386273a185be18857a12ab0305b753e50/index.d.ts#L140) and I would like to keep the same syntax, rather than having to resort to typecasting (i.e. `await response.json() as MyResponse`).

Is this something you would consider adding support for as well?

**Comment by sindresorhus** [comment]
Ky should already have this: https://github.com/sindresorhus/ky/blob/b86ff0a4e8d66c363df17612c968c023560f9241/index.test-d.ts#L132

**Comment by nielsdB97** [comment]
Ah I see, the type as you sent it indeed works fine when used like this:
```ts
ky(todoUrl).json<Todo>()
```
However I also want to keep metadata of the request, so I return the entire `ResponsePromise` from ky (omitting async for brevity):
```ts
fetchTodo() {
  return ky(todoUrl);
}
const res = fetchTodo();
res.json(); // This method does not support passing a generic
```
In this case the type for the `json` method is coming from the standard typescript lib.
Reproduced here: https://codesandbox.io/s/ky-response-type-wgy7s?file=/src/App.tsx

**Comment by sindresorhus** [comment]
Ah, yeah, I'm happy to merge a PR that fixes this.

**Comment by traverse** [comment]
I was thinking about taking a crack at this but I do have a question beforehand. @nielsdB97 I was wondering what your preference was with where to add the generic? Because in your sandbox example you can easily do the following.
```ts
ky("https://jsonplaceholder.typicode.com/todos/2").then((res) => {
  res.json().then((result: Todo) => {
    console.log(result);
  });
});
```
which would be similar to
```ts
const todo: Todo = await res.json()
```
You'll end up having to add the type everywhere though depending on how you use it. So even if the response has a `json` method that accepts a generic you would be adding it everywhere. So am I correct in assuming you would want the `ky` function to accept a generic which propagates to the `json` method on the response?

**Comment by nielsdB97** [comment]
@traverse Thanks for helping out!
In my project I have abstracted the HTTP layer into an `HTTPClient`, which has methods where I'd like to encapsulate fetching logic including what type will be returned.

In the basis, it looks like this:

```ts
const HTTPClient = ky.create({});

class APIClient {
  getTodos() {
    return HTTPClient.get("todos");
  }
}
```

I return the entire `ky` ResponsePromise type to keep metadata also available, next to the data response returned from ky's `json` method.
Now I'd like to be able to pass the type in the above code example already. [Axios makes this possible](https://github.com/axios/axios/blob/59ab559386273a185be18857a12ab0305b753e50/index.d.ts#L140) like so:

```ts
import type { Todo } from 'types';

class APIClient {
  getTodos() {
    return HTTPClient.get<Todo[]>("todos");
  }
}
```

**Comment by traverse** [comment]
@nielsdB97 Yeah that makes sense. Will start working on it if I have some time during the weekend. Have a basic idea of how to do it by extending `Response` and adding a generic and overwriting the `json` method.

**Comment by traverse** [comment]
I did some work on this during the weekend but ran into one hiccup. @sindresorhus I'm assuming you want the current behaviour of being able to add a type to the `.json()` call to stay the same for backwards compatibility? e.g.
```ts
ky(url).json<Todo[]>()
``` 
Which in turn would allow you to do the following.
```ts
ky<Todo>(url).json<Todo[]>()
```
I do however have an idea how to make this workable.

**Comment by mgcrea** [comment]
I've encountered this as well and think we should drop the generic for the `json()` method as it's awkward to be able to type both and people would expect first to be able to type the actual http method (`get/post/...`), it's just simpler.

It's how it is done for `got` as well and I think it makes sense to unify both APIs.

**Comment by zingerj** [comment]
Hi! I see that a PR was merged for this but it looks like `ky<Todo>(url).json()` still doesn't work. I instead have to do `ky(url).json<Todo>()` to get it to work, which I thought was already implemented prior to @TeraNovaLP's PR (based on [this comment](https://github.com/sindresorhus/ky/issues/312#issuecomment-752704273) above). Am I misunderstanding something? FWIW I do think `ky<Todo>(url).json()` would be a more intuitive API here. Thanks!

**Comment by osrl** [comment]
Hi, I also think that leveraging the type info to the call is more suitable. Enforcing the type on the call site instead of implementation is awkward. I'm also trying to abstract the API layer having the same issue. 

For example, I'm implementing the API layer.
```typescript
updateUser = () => {
    return ky('/api/profile');
};
```

the other developer has to know the return type.
```typescript
const response = await updateUser()

const newUser = response.json<User>();
const status = response.status
```

Instead we should be able to implement like this:
```typescript
updateUser = () => {
    return ky<User>('/api/profile');
};
```

on the call site:
```typescript
const response = await updateUser()

const newUser = response.json(); //the type is User
const status = response.status
```

**Comment by osrl** [comment]
this is a breaking change, I didn't wanted to open a PR for this but this is how to do it (I can open if you want me to)

```typescript
export interface KyResponse<T = any> extends Response {
	json: () => Promise<T>;
}
```

```typescript
export interface ResponsePromise<T = any> extends Promise<KyResponse<T>> {
	arrayBuffer: () => Promise<ArrayBuffer>;

	blob: () => Promise<Blob>;

	formData: () => Promise<FormData>;

	/**
	Get the response body as JSON.

	@example
	```
	import ky from 'ky';

	const json = await ky(…).json();
	```
	*/
	json: () => Promise<T>;

	text: () => Promise<string>;
}

```

```typescript
<T = any>(url: Input, options?: Options): ResponsePromise<T>;

get: <T = any>(url: Input, options?: Options) => ResponsePromise<T>;
```

**Comment by mr-rpl** [comment]
did this ever make it in? +1 to `ky<T>` being more intuitive than `.json<T>()`

i just installed the latest and seems to still be the latter

for backwards compat, you can always leave the .json one and simply add the ky generic... json if provided just takes priority

**Comment by GrtDev** [comment]
I just started with `ky` and this is something I really missed as well when preconfiguring certain endpoints. 
Right now I'm just overruling the response type.

```
type TypedJsonFunc<T> = {
    json: () => Promise<T>;
};

type TypedKyResponse<T = unknown> = Omit<ResponsePromise, 'json' | keyof Promise<unknown>> &
    TypedJsonFunc<T> &
    Promise<Omit<KyResponse, 'json'> & TypedJsonFunc<T>>;
 ```

**Comment by sholladay** [comment]
@adamJLev your wish is coming true: https://github.com/sindresorhus/ky/pull/619

TS experts, please chime in there if you have suggestions.
