### ISSUE TITLE
Reconsider dropping named exports

### ISSUE THREAD

**Issue by mgcrea** [sindresorhus/ky#320]
Just stumbled on #237 as I was trying to perform an `instanceof HTTPError` check. Having everything exported under a single default export is in my opinion a bit clumsy and it took me quite some time to find the `ky.HTTPError` workaround since it breaks intellisense and is a pretty rare pattern nowadays. It also seems to break `ky.create()` in TypeScript (see #256).

The whole ecosystem has clearly been embracing modules as the way forward for quite some time and I'm pretty sure that today, the large majority of frontend javascript developers are using them (either via babel or typescript) and not CommonJS directly.

Any chance we could reconsider this and move back to properly exported types?
Maybe if this is really wanted publish a dedicated patched build for commonjs users?

**Comment by sholladay** [comment]
We no longer officially support CommonJS so yes, I think it's fair to revisit this. I'm fine with exporting `HTTPError` and `TimeoutError` separately. The only one I'm a little hesitant about is `stop`. I feel that the name benefits from being read as `ky.stop` and is less clear on its own. But if this change makes things easier for people overall, it's probably worth it.

**Comment by sindresorhus** [comment]
I'm happy to have the error to be named exports. As for `ky.stop`, I agree, it will not be readable as just `stop`. I think the problem mention is only with the errors, so I think we can just leave `ky.stop` as-is.
