### ISSUE TITLE
NextJs 10 / ky 0.26.x can't compile esm

### ISSUE THREAD

**Issue by belgattitude** [sindresorhus/ky#322]
Since the new esm export landed in 0.26.x, import ky in nextjs break the build and dev

## What I did

Updated from 0.25.1 to 0.26.0, and renamed older umd imports `import ky from 'ky/umd'` into `import ky from 'ky'`.

## Environment:
- NextJs 10.0.6 / Typescript (babel)
- NodeJs 12.14.1
- Ubuntu 20.04 (probably the same everywhere)
- Vercel 

## Workaround

Adding next-transpile-module will help... see the config here https://github.com/belgattitude/profile-in-a-rush/blob/67fb6faa8ac9989c45d48d39c72f7d4a2b59aa7f/next.config.js#L4

```
const withTM = require('next-transpile-modules')(['ky']);
```

But it's far from ideal.

## Reproduce

See this example branch: https://github.com/belgattitude/profile-in-a-rush/pull/39

## Solution

If possible can you export multiple builds ? i.e: 

```
  "jsnext:main": "dist/ky.es.js",
  "module": "dist/ky.es.js",
  "esmodules": "dist/ky.modern.js",
  "main": "dist/ky.js",
  "umd:main": "dist/ky.umd.js",
  "types": "dist/index.d.ts",
```

Building with microbundle (or tsdx) would help. I had some good experience doing something [similar to this](https://github.com/soluble-io/cache-interop/blob/daf1cab90f2de8612d6f2091b0dd4818b7e6c239/packages/cache-interop/package.json#L34).

## Possible 

Haven't tested Jest, but it might affected as well. Not sure of the latest  esm support.

## Error message

```
.../node_modules/ky/index.js:510
export default ky;
^^^^^^

SyntaxError: Unexpected token 'export'

(node:24112) Warning: require() of ES modules is not supported.
require() of /..../node_modules/ky/index.js from ....next/server/pages/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename .../node_modules/ky/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from .../node_modules/ky/package.json.
.../node_modules/ky/index.js:510
export default ky;
^^^^^^

SyntaxError: Unexpected token 'export'
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module
```

**Comment by sindresorhus** [comment]
Please open an issue at https://github.com/vercel/next.js This is something Next.js needs to fix. Ky has correctly adopted ESM. A lot of packages are moving to ESM-only in April, so this problem is just going to get worse for Next.js. I don't have any plans to implement multiple builds. I recommend staying on the previous Ky version until Next.js improves the situation.

**Comment by belgattitude** [comment]
Fair and somehow appreciate the move :smile:.  Not sure if it's too early though.

For Next users, don't forget to add ky to next-transpile-modules, that will also allow older browser support.

*Linkto nextjs issue:  https://github.com/vercel/next.js/issues/9607#issue-531999825 and comment https://github.com/vercel/next.js/issues/9607#issuecomment-773885644*

**Comment by sholladay** [comment]
I know it's inconvenient for Node users since we're early adopters compared to the rest of the ecosystem, but FWIW browsers have supported ES modules for years. We waited a long time for Node to catch up and it finally did. We're eager to put CommonJS behind us. And Ky was never really designed to be used in Node anyway.

**Comment by belgattitude** [comment]
@sholladay Agree for browsers. But support is dependent of the build you use... Esm still not a thing in nextjs, don't know create-react-app, nuxt,.... event if it's a browser thing only.

For isomorphic support we tend to use ky-universal and the couple is actually fantastic. Same would be in newer versions of axios (but I feel ky is more reliable still, kudos to devs :smile:)

**Comment by Janpot** [comment]
@belgattitude in Node.js > v12, you should be able to `await import('ky')`, [even from commonjs modules](https://nodejs.org/api/esm.html#esm_import_expressions)
