### ISSUE TITLE
merging searchParams by ky.create() occurs unnecessary  headers  query string

### ISSUE THREAD

**Issue by TasukuUno** [sindresorhus/ky#324]
I want to set default search params by `ky.create()` and set another one at execution-time.
But, this use case occurs  unnecessary  `headers=%5Bobject+Object%5D`  query string.

## minimal example

https://codepen.io/TasukuUno/pen/KKNgNae?editors=0010

```js
const instance = ky.create({
  searchParams: {
    // a: 1
  },
});

const res = await instance.get('/some/api', {
  throwHttpErrors: false,
  searchParams: {
    // b: 2
  },
});

// actual request url: /some/api?headers=%5Bobject+Object%5D
console.log(res.url);
```

edited: here's another example repository I made 3 months ago (and forgotten 😅  )
https://github.com/TasukuUno/repro-ky

**Comment by Alexander-Pomazan** [comment]
Until this is fixed, I found that this is a viable workaround:

```
ky.create({
  beforeRequest: [
    (request: Request): Request => {
      const fixedUrl = request.url.replace("headers=%5Bobject+Object%5D&", "")
    
      return new Request(fixedUrl, request)
    }
  ]
})
```

**Comment by evolverine** [comment]
I'm still getting this issue (the headers object added to the searchParams) using the minified version of the 27.0 release. Code looks a bit like this:

``` ky.create({ prefixUrl: SERVER_URL, timeout: 2000, searchParams : { api_key : config.API_KEY } })).get(URL, {searchParams: {a : 1}})
