### ISSUE TITLE
How to set headers in post request?

### ISSUE THREAD

**Issue by fookit** [sindresorhus/ky#328]
Hi! New to Ky, thanks for the amazing library.

How do I set headers in post request?

My 1st attempt:

```ts
    await ky
      .post('/api/hi', { headers: { 'ping': 'pong' }, json: data })
      .json()
      .catch((e) => console.log(e))
```

2nd attempt with `.extend()`:

```ts
const apiKy = ky.extend({ headers: { 'ping': 'pong' } })

...

    await apiKy
      .post('/api/hi', { json: data })
      .json()
      .catch((e) => console.log(e))
```

None of those works. API server does not receive any from `req.headers['ping']`.

Please help, what I am doing wrong?

versions: ky (v0.26.0), ky-universal (v0.9.1)

**Comment by fookit** [comment]
I had to supply `headers` as last argument.

**Comment by fookit** [comment]
But it does not work all the times. :(

**Comment by sholladay** [comment]
Both of your attempts look correct to me. We have tests to prove this works.

 - https://github.com/sindresorhus/ky/blob/main/test/headers.js
 - https://github.com/sindresorhus/ky/blob/main/test/main.js
 - 
Could you provide a reproducible example, such as a GitHub repo, a CodeSandbox, or a PR with a failing test?

**Comment by sholladay** [comment]
@fookit I'd be happy to look into your issue, if you can respond to my question.

Until then I'm closing this for lack of information.
