### ISSUE TITLE
Warning on react-native: "Package ky has been ignored because it contains invalid configuration"

### ISSUE THREAD

**Issue by latobibor** [sindresorhus/ky#331]
#### The problem
When I start bundling the application I get a warning:
`Package ky has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/...`

#### Versions
* `react-native`: `0.63.2`,
* `ky`: `0.27.0`

Thanks!

**Comment by sindresorhus** [comment]
This is a React Native tooling bug: https://github.com/react-native-community/cli/issues/1168

We don't intend to work around it.

**Comment by felginep** [comment]
Sorry to reopen the issue, but is there any update on this ? 

I'm still facing it with `v0.28.5` and the React Native issue you linked above has no workaround other than patching each lib.

**Comment by sholladay** [comment]
I haven't heard of any updates from the React Native developers and that issue is still open.
