### ISSUE TITLE
Discrepancy between doc and types for searchparams options in v 0.28

### ISSUE THREAD

**Issue by jraoult** [sindresorhus/ky#343]
Following the recent refactoring to TS, the types for `PlainOptions.searchParams` became more restrictive than what is in the doc: https://github.com/sindresorhus/ky#searchparams

For us, our codebase fails to type-check when using boolean values in 0.28 (but was passing before):
```ts
ky.get(url, {
  // this fails in v0.28
  searchParams: { val: true },
  })
```

I'm happy to go ahead and update all the places where the compilation fails if it is an API design decision but before I wanted to check that it was intentional or wasn't an oversight?

**Comment by sindresorhus** [comment]
That sounds like a regression.

// @mgcrea
