### ISSUE TITLE
Options type is not exported anymore

### ISSUE THREAD

**Issue by mcchrish** [sindresorhus/ky#347]
```ts
import ky, { Options } from 'ky'
```

It was available in 0.27 but not in 0.28.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ky/releases/tag/v0.28.2

**Comment by ux-engineer** [comment]
@sindresorhus 
NormalizedOptions still not exported in Ky types? On 0.27 these all could be imported from 'ky', but now on 0.28.4 I'm needing this:

```
import type { BeforeRequestHook, BeforeRetryHook, AfterResponseHook } from 'ky';
import type { NormalizedOptions } from 'ky/distribution/types/options';
```

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ky/commit/2d8d68ae08f974d5e04249076683ec763d647bf5 made a bit of mess of things.

Fixed: https://github.com/sindresorhus/ky/releases/tag/v0.28.5
