### ISSUE TITLE
Adding json methods

### ISSUE THREAD

**Issue by jodiedunlop** [sindresorhus/ky#35]
To simplify json calls, which is probably the major use-case of this library it might be nice to provide some wrapper methods which simplify the api calls even further for the common get, put, patch, delete http verbs.

Eg. 
```
const json = await ky.getJson('https://some-api.com');
const json = await ky.postJson('https://some-api.com', {foo: true});
```
These would obviously just be some syntatic sugar around the existing json examples, but imo it would make the api even nicer to use.

**Comment by sindresorhus** [comment]
To make it clear, you won't save many characters with your proposal. 1 character to be exact. You can't really pass a plain object into the second one as we need to support options too. So would be:

```js
const json = await ky.getJson('https://some-api.com');
const json = await ky.postJson('https://some-api.com', {json: {foo: true}});
```

vs. Ky now:

```js
const json = await ky('https://some-api.com').json();
const json = await ky.post('https://some-api.com', {json: {foo: true}}).json();
```

The current Ky syntax is almost the same size, but is much more flexible. You can decide to send JSON, but receive something else, all without having to learn a different API.
