### ISSUE TITLE
Can't Override Prefix URL in beforeRequest hook

### ISSUE THREAD

**Issue by LuisOsta** [sindresorhus/ky#350]
So I'm trying something like this:

```
const createKyInstance = () => {
  if (process.env.NODE_ENV === "development") {
    return ky.create({
      prefixUrl,
      credentials: "include",
      hooks: {
        beforeRequest: [
          (request, options) => {
            const isInBrowser = typeof window !== "undefined";
            options.prefixUrl = isInBrowser ? prefixUrl : serverSideUrl;
          },
        ],
      },
    });
  } else {
    return ky.create({
      prefixUrl,
      credentials: "include",
    });
  }
};

```

In order to get Next.js to work in Docker (the endpoint between client and server-side execution needs to be different)

This doesn't work as the request will use the `request.url`, Which has the full url with the previously used prefixURL. And since that property is read-only we can't override it.

**Comment by sholladay** [comment]
The hook doesn't seem necessary. `isInBrowser` presumably won't change between requests. Why not just do `prefixUrl : isInBrowser ? ...` in the `ky.create()` options?

**Comment by LuisOsta** [comment]
Actually, it will because I'm using Next.js. So the serverside code (getServerSideProps, etc). Is executing inside the docker container while the client-side code is executing in the browser.

Hence we need to, at request time, determine which environment it's in as to use the correct prefix

**Comment by sholladay** [comment]
But those are two separate instances. Each one is always bound to a single environment. If you add a `console.log()` to you `createKyInstance{}` function, surely it will log once on the server and once on the client, right? If so, you don't need per-request configuration.

**Comment by LuisOsta** [comment]
Yeah, you're correct, after investigation, it seems that just customizing the prefix URL per environment will do the job. I'll close the issue since it's not an issue for my use case.
