### ISSUE TITLE
beforeRequestFn processing changed after 0.28.2 > 0.28.3 upgrade

### ISSUE THREAD

**Issue by ux-engineer** [sindresorhus/ky#354]
Trying to debug a problem which does not appear with 0.27.0 but after 0.28.x upgrade... As used in conjunction with vuex-oidc (oidc-client) library.

When login finished and userLoaded event is triggered by oidc-client, in it's event handler we are doing a request for additional user details. Access token is added to the request in a beforeRequest hook function.

After the upgrade, access token is not yet available in store and the request fails with 401 Unauthorized as bearer token is missing.

After adding a temporary fix of doing 50ms delay before triggering the additional user details request, then the access token is available in the beforeRequest hook function.

Verified this is about Ky library as after downgrading from 0.28.5 to 0.27.0 this problem disappears...?

**Comment by ux-engineer** [comment]
@sholladay alright, so I have narrowed the issues' appearance after upgrading from 0.28.2 to 0.28.3

**Comment by ux-engineer** [comment]
So it seems that this is related to that 1 millisecond wait on this commit: https://github.com/sindresorhus/ky/commit/5f3c3158af5c7efbb6a1cfd9e5f16fc71dd26e36

**Comment by ux-engineer** [comment]
https://github.com/sindresorhus/ky/issues/345

**Comment by szmarczak** [comment]
@ux-engineer Can you try `await new Promise(queueMicrotask)` and see if it helps?

**Comment by ux-engineer** [comment]
@szmarczak interesting wait function syntax! However its not working on TS as `queueMicrotask` types are waiting for a callback function.

I did make a temporary fix by running `await sleep(2);` before fetching, and it is working - but perhaps not ideal solution.

```typescript
// Async sleep function
export const sleep = function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
};
```

**Comment by szmarczak** [comment]
> its not working on TS as queueMicrotask types are waiting for a callback function.

Hmm it works here:
https://www.typescriptlang.org/play?#code/BQQwzgngdgxgBMAlHAvAPjgbwLACg4FwgDuIAlgC5xQCmxcACgE4D2AtmWDQDwBuLZACZpgARwCuNSQFkyMVhXABrRAG48AX0RJVQA

**Comment by ux-engineer** [comment]
@szmarczak ah, there was a type parameter, so this is working and is nice clean syntax 👍 

```ts
await new Promise<void>(queueMicrotask);
```

**Comment by sholladay** [comment]
Now the question is, will that break New Relic? 🤔 

At least this one seems like it should be testable.

**Comment by ux-engineer** [comment]
So it seems our implementation, although restricted by `vuex-oidc` / `oidc-client-js` libraries with which we need to run fetch in event handler callback function code, and there is only one possibility, so no other event runs after their library has guaranteed'ly written access key to store module.

Unless perhaps we could use watcher on that store module's getter, but it needs to set up on layout component level... Do you can come up with other ideas?

**Comment by szmarczak** [comment]
@smblee @lukeupup Can you check the `queueMicrotask` workaround above?

**Comment by ux-engineer** [comment]
Sorry, it seems `queueMicrotask` await is not lengthy enough a duration. I seem to have missed something when testing this last night.

**Comment by sholladay** [comment]
I'll try to find another solution @ux-engineer but would it be possible for you to submit a PR with a test case?

Example: https://github.com/sindresorhus/ky/blob/main/test/main.ts

**Comment by sholladay** [comment]
Closing because I think we're going to keep the current implementation of using `await Promise.resolve()` to delay the request, unless anybody has another suggestion. The only true fix I'm aware of would involve redesigning the public API from `ky().json()` to something like `ky.json()`.
