### ISSUE TITLE
package.json file missing from exports

### ISSUE THREAD

**Issue by heikkilamarko** [sindresorhus/ky#360]
I'm using `Ky` in a Svelte app. I use Vite as the frontend tooling.
`npm run build` gives the following warning:

```
[vite-plugin-svelte] The following packages did not export their `package.json` file so we could not check the "svelte" field. If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.
- ky
```

**Comment by sindresorhus** [comment]
> then please contact the author and ask them to export the package.json file.

I'm sorry that your tool is misleading you, but this is entirely a problem with `vite-plugin-svelte`. Packages are not expected to export `package.json` and tools should not rely on it. I would recommend opening an issue on `vite-plugin-svelte` instead.
