### ISSUE TITLE
[DEP0151] DeprecationWarning under Node.js 16

### ISSUE THREAD

**Issue by faty2** [sindresorhus/ky#365]
[DEP0151] DeprecationWarning: No "main" or "exports" field defined in the package.json for /Users/chenxi/Desktop/imufu/xingmeiji-solver/node_modules/ky/ resolving the main entry point "index.js"

package.json

add line after type:
"type": "module",
**"main": "index.js",**

**Comment by szmarczak** [comment]
We have `main` here: https://github.com/sindresorhus/ky/blob/870a0b29d925df1873d85fcb449cf6e13d03ca0c/package.json#L14

**Comment by szmarczak** [comment]
There's no deprecation message in the tests running on Node.js 14: https://github.com/sindresorhus/ky/runs/2845915802#step:5:1

**Comment by faty2** [comment]
> There's no deprecation message in the tests running on Node.js 14: https://github.com/sindresorhus/ky/runs/2845915802#step:5:1

there is no problem with versions below 16

**Comment by szmarczak** [comment]
What version are you using? I can't reproduce with latest.

**Comment by faty2** [comment]
> What version are you using? I can't reproduce with latest.

(node:3220) [DEP0151] DeprecationWarning: No "main" or "exports" field defined in the package.json for /test/node_modules/ky/ resolving the main entry point "index.js", imported from /test/node_modules/ky-universal/index.js.
Default "index" lookups for the main are deprecated for ES modules.

all  16 version, i‘m using 16.6.0 now

**Comment by faty2** [comment]
> What version are you using? I can't reproduce with latest.

sorry, my mistake, i'm using version 0.26. It's normal to upgrade to the latest version.

**Comment by faty2** [comment]
upgrade to the latest version
