### ISSUE TITLE
Allow custom content-type header to be set

### ISSUE THREAD

**Issue by brighttank** [sindresorhus/ky#369]
For some reason Amazon REST api's require the content-type to be set to "application/x-amz-json-1.1" instead of the standard "application/json"

Currently the content-type header is set automatically for json data overriding any headers passed in to the request.

It would be useful to first check if the header is set before overriding it:
```
if (!this.request.headers.set('content-type')) {
    this.request.headers.set('content-type', 'application/json');
}
```

**Comment by sindresorhus** [comment]
If anyone wants to works on this, see the initial attempt in https://github.com/sindresorhus/ky/pull/382.
