### ISSUE TITLE
How to send FormData with application/json?

### ISSUE THREAD

**Issue by Stedioz** [sindresorhus/ky#373]
How to send FormData with application/json?
This:
```
let formData = new FormData("formID");
ky.post(action, {throwHttpErrors: false, json: formData}).json();
```
sends empty body
This:
`ky.post(action, {throwHttpErrors: false, json: {formData}}).json();`
sends formData: {}
But formData is NOT empty!

**Comment by szmarczak** [comment]
JSON is JSON. JSON is not FormData, you're connecting the wrong dots.

https://github.com/sindresorhus/ky#sending-form-data
