### ISSUE TITLE
Example for Typescrip

### ISSUE THREAD

**Issue by IRediTOTO** [sindresorhus/ky#377]
Hi, can you make an example for Typescript? 
I want to setup what can be response type.

**Comment by belgattitude** [comment]
From axios, you move the generic in the json method.

```typescript
ky.get('/api')
    .json<JsonApiResponse<GetPosts>>()
    .then((resp) => {
        //...
    });
};
```

Where in axios it's on the get method

```typescript
axios
    .get<JsonApiResponse<GetPosts>>('/api')
    .then((resp) => {
      //...
    });
```

There's also some discussion here https://github.com/sindresorhus/ky/issues/312

**Comment by IRediTOTO** [comment]
> From axios, you move the generic in the json method.
> 
> ```ts
> ky.get('/api')
>     .json<JsonApiResponse<GetPosts>>()
>     .then((resp) => {
>         //...
>     });
> };
> ```
> 
> Where in axios it's on the get method
> 
> ```ts
> axios.get<JsonApiResponse<GetPosts>>('/api')
>           .then((resp) => {
>              //...
>           });
> ```
> 
> There's also some discussion here #312

Thank you so much :D Do you have any exp with organization large APIs, create a model can use to call api any where in workspace ? Is ther any example for it?

**Comment by belgattitude** [comment]
Not opensource unfortunately. 

But for the workspace idea,  you might find this useful https://github.com/belgattitude/nextjs-monorepo-example. That said there's very little examples of api there, I might add some in the future.
