### ISSUE TITLE
multiple response headers with the same name are being clobbered

### ISSUE THREAD

**Issue by twelve17** [sindresorhus/ky#378]
I'm testing a request to a site that returns multiple `set-cookie` headers.  With `ky`, I am only seeing one of the headers.  Does `ky` support fetching all the header entries in the response that share the same name?

**Comment by sindresorhus** [comment]
This is a limitation with the Fetch standard:

- https://stackoverflow.com/questions/63204093/how-to-get-set-multiple-set-cookie-headers-using-fetch-api
- https://github.com/whatwg/fetch/issues/506#issuecomment-395756703

**Comment by twelve17** [comment]
@sindresorhus if I'm reading that SO article correctly, all the values from the multiple headers exist in the merged header. I am not seeing this when using ky. Are you able to?

**Comment by twelve17** [comment]
@sindresorhus hmm, I see in the other responses in that thread, the additional complications specific to `Set-Cookie`. What a shame. Thanks for the pointer.
