### ISSUE TITLE
Allow providing custom global methods

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/ky#385]
To prevent the prototype pollution present in `ky-universal`, `ky` should accept globals as an option. Perhaps the option name could be a symbol since it is unlikely anyone will actually want to use this option outside of this specific use case.

**Comment by Richienb** [comment]
It patches the global scope with polyfills. Libraries patching globals is always a bad idea.

**Comment by sholladay** [comment]
Closing due to lack of response.
