### ISSUE TITLE
"Require Cycle" warn while using "ky" with "react-native"

### ISSUE THREAD

**Issue by ArnabXD** [sindresorhus/ky#386]
I am using ky with react native and whenever I make a request I got a warning. 

```
Require cycle: node_modules\react-native\Libraries\Network\fetch.js -> node_modules\whatwg-fetch\dist\fetch.umd.js -> node_modules\react-native\Libraries\Network\fetch.js 
```

ky version: `^0.28.6`
react-native version: `0.65+` (I am not sure about the previous versions)

Normally `fetch` works fine.

**Comment by sindresorhus** [comment]
There not enough information here to do anything with it. I also doubt it's a problem with this package.
