### ISSUE TITLE
Missing "sourcesContent" in source map

### ISSUE THREAD

**Issue by zengguirong** [sindresorhus/ky#395]
In the source map file, I found the `sources` field that is pointing to the source location (such as https://cdn.jsdelivr.net/npm/ky@0.28.6/distribution/index.js.map). But the source folder is not inclued in the published package.
When using some esm bundlers such as `Vite`, the dev server could not find the source file and finally response error with code 404.
There is 2 resolution:
1. Set the `inlineSources` option to true in tsconfig.dist.json
2. Add `source` to the `files` field in package.json

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/ky/pull/396
