### ISSUE TITLE
Maybe some assertions for `defaults` type in `extend`?

### ISSUE THREAD

**Issue by poppinlp** [sindresorhus/ky#40]
The `defaults` param will be used to `deepMerge` with other options and the `deepMerge` method will flat items for array argument.
Everything goes on normal and users may not know what happen if they pass in an array until they look into code. But there is something changed for options for `Ky` constructor actually.
Maybe there could be some assertions for the `defaults` param type as it should be an object? :)

**Comment by sindresorhus** [comment]
Sure, good idea. PR welcome.
