### ISSUE TITLE
prefixURL not working correctly when used as environmental variable

### ISSUE THREAD

**Issue by DanielKlys7** [sindresorhus/ky#400]
Working on `localhost:3000`, `.env` contains `REACT_APP_API_URL=​https://www.reddit.com/`

Whenever we want to make a request using this client:

```
export const client = ky.create({
  prefixUrl: process.env.REACT_APP_API_URL,
});
```
it is made to `http://localhost:3000/%E2%80%8Bhttps://www.reddit.com/r/music/new.json 404 (Not Found)`

if `prefixUrl` is set to api directly in `create` options parameter, everything works fine.

**Comment by sindresorhus** [comment]
> if prefixUrl is set to api directly in create options parameter, everything works fine.

I think this is a pretty clear sign that the issue is not with Ky.

**Comment by sindresorhus** [comment]
Looks like the environment variable value includes some hidden spaces.

Try `process.env.REACT_APP_API_URL` => `process.env.REACT_APP_API_URL.trim()`
