### ISSUE TITLE
HTTP2 (h2) support

### ISSUE THREAD

**Issue by mohsenomidi** [sindresorhus/ky#407]
Is there any plan to add HTTP/2 support for browser?

**Comment by sindresorhus** [comment]
HTTP support follows what the browser supports. Most modern browsers support HTTP/2: https://caniuse.com/?search=http2

**Comment by mohsenomidi** [comment]
Thanks for your reply 

I mean how can I use the http2 multiplexing option for api call with ky, in my react pages I have about 10 api call and normally each one make its own connection to single backend I want to achieve the multiplexing benefits from client side, is it possible with ky?

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/ky/issues/407#issuecomment-997438044
