### ISSUE TITLE
Got a typescript issue with ky

### ISSUE THREAD

**Issue by MatteoGauthier** [sindresorhus/ky#413]
```
Property 'ok' does not exist on type 'unknown'
```

```ts
const facadeEdited = await ky.put(`/api/facade/${"facade-1"}`, { json: data }).json()
if (facadeEdited.ok) {

}
```

Does someone can help me ?

**Comment by sindresorhus** [comment]
What have you tried? Generally when you encounter issues like this, it's smart to read the docs. Opening an issue should be the last resort.

In this case, `facadeEdited` is the response body, NOT the response. There's no `ok` property unless the actual response body contains it, and if so, you have to cast it to the correct type.
