### ISSUE TITLE
Empty 204 response throw error - 0.31.0

### ISSUE THREAD

**Issue by parafeu** [sindresorhus/ky#443]
Hello ! 

After the 0.31.0 update, 204 responses with empty content throw the following exception :

![image](https://user-images.githubusercontent.com/39409783/177943880-82e3c66e-caea-4053-a53b-1d9ef7ce8e25.png)

Here is my code : 

```ts
 public static async login(data: LoginData) {
      await fetch.post('login', {
          json: {
              ...data,
              cookie: true
          }
      });
}
```

This happens on both Firefox and chromium-based browsers.

**Comment by sindresorhus** [comment]
@promer94 @TeraNovaLP This may be caused by https://github.com/sindresorhus/ky/commit/f34fb1fabcdcffc93372da08e721d0864db771ba or https://github.com/sindresorhus/ky/commit/cff4c7ae0aafbbda4d3b01945943d844527939ba
