### ISSUE TITLE
source contains non-free font Optima

### ISSUE THREAD

**Issue by jonassmedegaard** [sindresorhus/ky#447]
Source file `media/logo.ai` embeds the font Optima which is owned by Adobe and not freely licensed.

Please either remove the logo (also the other files which then lack source), or somehow avoid depending on the non-free font.

**Comment by sindresorhus** [comment]
I have changed it to the version of Optima that is free for non-commercial use.

**Comment by jonassmedegaard** [comment]
Thanks for looking into this.

Please beware that licensing which excludes non-commercial use is considered non-free by GNU and Debian and OSI - i.e.  all major definitions of Free and Open Source software.

**Comment by sindresorhus** [comment]
The font is only used in this repo. It's not part of the package.

**Comment by jonassmedegaard** [comment]
Sounds like you've made up your mind.

I will then have the slight hassle of repackaging the code for Debian redistribution (which I am currently preparing), and expect other distributions to need to do the same.

Thanks for at least considering - and for writing this code project in the first place. Much appreciated!
