### ISSUE TITLE
Respect Retry-After response header

### ISSUE THREAD

**Issue by rifler** [sindresorhus/ky#45]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After

**Comment by sindresorhus** [comment]
For anyone that would like to work on this, see https://github.com/sindresorhus/got/pull/508#issuecomment-404196389 and how it's implemented in Got: https://github.com/sindresorhus/got/blob/a07b2beb3af302743108ca67c145531117ef6a95/source/normalize-arguments.js#L233-L260

Could take its tests too: https://github.com/sindresorhus/got/blob/25f18be291dd866a37f5153ca76d44151fcd702b/test/retry.js

**Comment by sindresorhus** [comment]
@komcal Go ahead :)
