### ISSUE TITLE
Chrome@105 Failed to construct Request The duplex member must be specified

### ISSUE THREAD

**Issue by karol-f** [sindresorhus/ky#450]
Chrome@105 Failed to construct Request The duplex member must be specified.

> From Chromium 105, you can start a request before you have the whole body available by using the Streams API.

https://developer.chrome.com/articles/fetch-streaming-requests/
![screenshot_998](https://user-images.githubusercontent.com/893082/187879618-c911e87c-08ec-4e44-a75f-1836abae5386.jpg)

Tested on Ky@0.28.5 and lates Ky@0.31.1

It seems that 
```
duplex: 'half'
```

option is missing.

**Comment by karol-f** [comment]
I've prepared a dummy [Pull Request](https://github.com/sindresorhus/ky/pull/451) with changes needed to make it work. I'm sure this can be improved.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ky/releases/tag/v0.31.2

**Comment by karol-f** [comment]
Thank You!

**Comment by patrick-entinux** [comment]
FYI the core issue seems to have been on this line: https://github.com/sindresorhus/ky/blob/da40323e903fb943c9192e4a43f9dc601d16a5e8/source/core/Ky.ts#L180

I found a related bug report for Chrome here: https://bugs.chromium.org/p/chromium/issues/detail?id=1360943&q=duplex&can=2#makechanges and added a comment explaining how it can affect old versions of "ky". 

(Actually now that I have discovered this issue, I have to check a few different apps to see if they are using "ky" and will be affected...)
