### ISSUE TITLE
`DOMException` returned from `composeAbortError` does not have name AbortError

### ISSUE THREAD

**Issue by janerikbr** [sindresorhus/ky#470]
## Description
After upgrading to `ky` 0.32, errors thrown as a result from calling `abortController.abort` does no longer have name "AbortError", just "Error", making it hard to distinguish between AbortErrors and other errors. This seems to be caused by the fact that `composeAbortError` does not provide a second parameter `name` when constructing a new `DOMException`: https://github.com/sindresorhus/ky/blob/e791d16b27549e89134e446a90bf1b8307749ef0/source/errors/DOMException.ts#L7

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort), promises rejected as a result of calling abort should have the name AbortError.

> When abort() is called, the fetch() promise rejects with an Error of type DOMException, with name AbortError.

I may be missing something here – but shouldn't the `DOMException` created in `composeAbortError` be given the name AbortError?

```js
return new DOMException(signal?.reason ?? 'The operation was aborted.', 'AbortError')
```

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/ky/pull/482
