### ISSUE TITLE
`browser` file is emitted on Webpack and Babel umd library build

### ISSUE THREAD

**Issue by nugaon** [sindresorhus/ky#471]
### Summary
Using Webpack and Babel `umd` build, the library produces `browser` file for both browser and node environment.
Even stranger is that it emits this file multiple times at node build that also causes error for the process.

You can reproduce it by cloning [this repo](https://github.com/fairDataSociety/bee-js/pull/50) and running `npm i`.

### Origin story
One of our dependencies had to update this library because of [the missing `duplex` member in the request](https://github.com/ethersphere/bee-js/issues/762).
The library also became ESM that we tried to import into our library after which it did not work with [Jest tests](https://github.com/fairDataSociety/fdp-storage/pull/179).
Now, there are attempts to build this dependency with our stack that you can see above in order to have Jest tests.

**Comment by sindresorhus** [comment]
You should ask this question in the Webpack issue tracker instead. This is about Webpack, not Ky. We are just using the standard package.json exports config.
