### ISSUE TITLE
Error 1101 on `esm.sh`

### ISSUE THREAD

**Issue by scarf005** [sindresorhus/ky#481]
## https://esm.sh/ky
![image](https://user-images.githubusercontent.com/54838975/211445517-96b06faa-3940-46a3-a5ae-5662e5915c43.png)

## https://esm.sh/react@18.2.0
![image](https://user-images.githubusercontent.com/54838975/211445482-3682bffb-45c8-4635-9db5-694c757a9b1b.png)
other packages work.

**Comment by sindresorhus** [comment]
You should report esm.sh issues to them, not here. There's nothing we can do about esm.sh issues.

**Comment by sindresorhus** [comment]
It seems to work now though, so must have been a temporary issue.

**Comment by scarf005** [comment]
oh, thanks for clarifying. didn't know it was esm issue.
