### ISSUE TITLE
TypeError: The "emitter" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal

### ISSUE THREAD

**Issue by himself65** [sindresorhus/ky#498]
```sh
TypeError: The "emitter" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal
    at new NodeError (node:internal/errors:399:5)
    at getEventListeners (node:events:914:9)
    at new Request (node:internal/deps/undici/undici:7138:17)
    at new Ky (file:///Users/himself65/Code/AFFiNE/node_modules/ky/source/core/Ky.ts:178:18)
    at Function.create (file:///Users/himself65/Code/AFFiNE/node_modules/ky/source/core/Ky.ts:24:14)
    at Function.ky.<computed> [as post] 
```

Upstream: https://github.com/nodejs/undici/pull/1910

**Comment by belden** [comment]
@himself65 / @sindresorhus this was the first search result for an error I saw when upgrading my application (which **does not** use this project) from node-16 to node-18.

I see that this project tries to use node-14, and I wonder whether @himself65 was using this with node >= 18 when encoutering this issue.

I don't have a solution for my upgrade yet but wanted to share what I know so far.

**Comment by himself65** [comment]
I think this is a bug in the old nodejs 18 version, now it seems to be fixed

**Comment by himself65** [comment]
Solution https://github.com/nodejs/undici/pull/1910#issuecomment-1500332168

**Comment by sholladay** [comment]
Closing due to upstream fixes.
