### ISSUE TITLE
Version 0.32.2 broke Ky in react native

### ISSUE THREAD

**Issue by hamdiwanis** [sindresorhus/ky#502]
I thought it would be helpful to create an issue in case anyone wanted to address this issue.

This PR https://github.com/sindresorhus/ky/pull/466 used `.arrayBuffer()` on the response to count the byte length and check if its empty which is not implemented in RN which resulted in this error:

`Error: FileReader.readAsArrayBuffer is not implemented`

**Comment by sindresorhus** [comment]
React Native is not supported. It's up to your to polyfill missing methods if you need to use it there.

**Comment by hamdiwanis** [comment]
Good to have this stated to be clear. Thanks anyway.

**Comment by mzanini** [comment]
I am experiencing the same issue. Any workaround?
