### ISSUE TITLE
Loader problem 

### ISSUE THREAD

**Issue by Genarito** [sindresorhus/ky#505]
I was using the `0.30.0` version of Ky and everything was fine. Then I updated it to the `0.33.3` version and I'm getting this error:

```
ERROR in ./node_modules/ky/distribution/core/Ky.js 118:59
Module parse failed: Unexpected token (118:59)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|                 afterResponse: [],
|             }, options.hooks),
>             method: normalizeRequestMethod(options.method ?? this._input.method),
|             // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
|             prefixUrl: String(options.prefixUrl || ''),
 @ ./node_modules/ky/distribution/index.js 2:0-34 7:35-37 10:41-43
 @ ./src/components/institutions/InstitutionsPanel.tsx
 @ ./src/institutions.tsx
```

I tried configuring babel-loader in my Webpack config without results:

```js
{
    test: /\.(?:js|mjs|cjs)$/,
    exclude: /node_modules/,
    use: {
        loader: 'babel-loader',
        options: {
            presets: [
                ['@babel/preset-env', { targets: 'defaults' }]
            ],
            plugins: ['@babel/plugin-proposal-class-properties']
        }
    }
},
```

I there any detail I'm missing? Thanks in advance

**Comment by Genarito** [comment]
Ok, I'll try a new version of Webpack, thank you

**Comment by worc** [comment]
this seems like a general issue throughout the npm space where libraries are moving on to ESM but not every compiler config out there is going to be able to handle a mix of UMD and ESM, not without a decent amount of reconfiguration. and it's a pain in spaces where you don't have access to or control over your compiler settings

https://github.com/sindresorhus/ky/pull/315

**Comment by sholladay** [comment]
If you are restricted to some old build system that isn't compatible with modern JS syntax then you really need to be careful about which dependencies you are using. It certainly is a pain. My advice is to switch to esbuild if you can, as everything mostly "just works", whether your dependencies are new or old. You're almost always going to have an easier time changing your build system than convincing all of your dependencies to publish a module with your exact syntax and module format requirements.

**Comment by Genarito** [comment]
Hi! Thanks for the advice, but I've got a lot of Webpack config and plugins, so I can't switch. Also, I don't understand why this doesn't work as I'm using modern JS in my own files... I tried to configure some loaders but no luck
