### ISSUE TITLE
Can't set user agent header

### ISSUE THREAD

**Issue by b1ek** [sindresorhus/ky#510]
Hey y'all. I am sending the request like this:

```
await ky('http://url.com/api', {
    headers: {
        "User-Agent": "MySuperDuperCoolApp/4.2"
    }
}
```

And yet nginx log says the following:

```
127.0.0.1 - - [06/Jun/2023:11:04:44 +0000]  200 "GET /api HTTP/1.1" 1 "-" "undici" "-"
```

**Comment by sindresorhus** [comment]
I assume you are testing in a Chrome or Chrome-based browser, which does not support setting ``User-Agent`: https://bugs.chromium.org/p/chromium/issues/detail?id=571722

**Comment by b1ek** [comment]
> I assume you are testing in a Chrome or Chrome-based browser, which does not support setting `User-Agent`: https://bugs.chromium.org/p/chromium/issues/detail?id=571722

It actually happened in Firefox

**Comment by sindresorhus** [comment]
We have a test for this, so the problem is not in Ky: https://github.com/sindresorhus/ky/blob/356d61c1534c9dc2cfb8ce1c1ff5c4832579e11b/test/headers.ts#L42-L48
