### ISSUE TITLE
Always get error TypeError: Failed to fetch

### ISSUE THREAD

**Issue by naivefun** [sindresorhus/ky#513]
I'd expect the error could be several kinds of type, but the catched exception is always `TypeError: Failed to fetch`. Is there options wrong?

I need access error code like `ERR_NETWORK` `ERR_TOO_MANY_REDIRECTS` etc .... 

`test.js`
```javascript
import ky from "ky";

ky("https://www.githubbbbbb.com")
  .text()
  .catch((e) => {
    console.log(e.name, e.message);
  });
```

run `node test.js` and it prints out `TypeError fetch failed`

![image](https://github.com/sindresorhus/ky/assets/10683378/d1550b26-ea22-4edb-8525-e09a4c15b558)

**Comment by sholladay** [comment]
Fetch often throws very vague errors, unfortunately.

Try in a different browser. I find that Firefox and Safari in particular is usually the most informative.

**Comment by sindresorhus** [comment]
We cannot do anything about the errors Fetch throws.

Share your opinions here: https://github.com/whatwg/fetch/issues/526
