### ISSUE TITLE
How can I use a proxy like in axios?

### ISSUE THREAD

**Issue by MiniSuperDev** [sindresorhus/ky#526]
```ts
axios({
  proxy: {
    protocol: 'https',
    host: '127.0.0.1',
    port: 9000,
    auth: {
      username: 'mikeymike',
      password: 'rapunz3l'
    }
})
```

Thanks

**Comment by sindresorhus** [comment]
If this is about Node.js, https://github.com/gajus/global-agent is usually the go to tool for this, unfortunately, it doesn't yet support: https://github.com/gajus/global-agent/issues/52

Proxy support is not something we plan to or can support built-in here.

**Comment by transitive-bullshit** [comment]
From what I've found, the easiest way to use a proxy with Node.js `fetch` (and hence `ky`) is via undici's experimental [EnvHttpProxyAgent](https://github.com/nodejs/undici/blob/main/docs/docs/api/EnvHttpProxyAgent.md), which will respect the `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` environment variables.

```
npm install undici
```

```ts
import { EnvHttpProxyAgent } from 'undici'
import ky from 'ky'

const kyWithProxy = ky.extend({ dispatcher: new EnvHttpProxyAgent() })
```

This obviously won't work outside of Node.js, but it's still useful to know about.

**Comment by rdrigos** [comment]
> From what I've found, the easiest way to use a proxy with Node.js `fetch` (and hence `ky`) is via undici's experimental [EnvHttpProxyAgent](https://github.com/nodejs/undici/blob/main/docs/docs/api/EnvHttpProxyAgent.md), which will respect the `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` environment variables.
> 
> ```
> npm install undici
> ```
> 
> import { EnvHttpProxyAgent } from 'undici'
> import ky from 'ky'
> 
> const kyWithProxy = ky.extend({ dispatcher: new EnvHttpProxyAgent() })
> This obviously won't work outside of Node.js, but it's still useful to know about.

Good morning, how could I configure an HTTPS agent in the request? I know that in Axios I can do it this way (the way I am currently using):

```
const pemCertificatePath: string = path.join(process.cwd(), util.format('certificates/%s', env.COUPA_CERT_PEM));
const keyCertificatePath: string = path.join(process.cwd(), util.format('certificates/%s', env.COUPA_CERT_KEY));

this.api = Axios.create({
  baseURL: env.COUPA_API_URL,
  httpsAgent: new https.Agent({
    cert: fs.readFileSync(pemCertificatePath),
    key: fs.readFileSync(keyCertificatePath),
    rejectUnauthorized: false,
  }),
});
```

Since I plan to switch from Axios to Ky, how could I configure the certificates?
