### ISSUE TITLE
"fetch() request with GET/HEAD/OPTIONS method cannot have body" in Bun

### ISSUE THREAD

**Issue by dimonnwc3** [sindresorhus/ky#527]
Following code throws an error:
```
const res = await ky.post(baseURL("/api/v1/countries"), {
      json: { email: "aaaaaaa", name: "a" },
})
```

```
TypeError: fetch() request with GET/HEAD/OPTIONS method cannot have body.
code: "ERR_INVALID_ARG_VALUE"
```

```
❯ bun --version
1.0.2
```

```
"ky": "^1.0.1",
```

**Comment by sindresorhus** [comment]
I recommend opening an issue on Bun. We have a test to prove it works fine in Node.js: https://github.com/sindresorhus/ky/blob/98d76e6d0827504b0f5574693eaa3feec664f06c/test/fetch.ts#L62-L66

**Comment by dimonnwc3** [comment]
resolved with this: https://github.com/oven-sh/bun/issues/6144
