### ISSUE TITLE
retry is wrongly counting

### ISSUE THREAD

**Issue by Kikobeats** [sindresorhus/ky#528]
I wrote a library that can use ky or got as an HTTP client.

I wanted to verify retries are consistent. To be sure about hat, I wrote a little server that counts retries:

```js
let retryCount = -1
let last 

const server = require('http').createServer((req, res) => {
  if (Date.now() - last > 5000) retryCount = -1
  ++retryCount
  res.statusCode = 500
  console.log({ retryCount })
  last = Date.now()
  res.end(String(retryCount))
})

server.listen(4000, () => {
  console.log('> Listening at http://localhost:4000')
})
```

Then, I setup my code with `{ retry: 3 }`

Using `got`:

```js
{ retryCount: 0 } // first request
{ retryCount: 1 }
{ retryCount: 2 }
{ retryCount: 3 }
```

Using `ky`:

```js
{ retryCount: 0 } // first request
{ retryCount: 1 }
{ retryCount: 2 }
```

As you can see, ky is counting the first request as retry while retry should be counter _after_ the first request is performed.

I'm opening this issue since it's unsure if that is intentional; My fix was to count +1 in the case of ky:
https://github.com/microlinkhq/mql/pull/130/

**Comment by sindresorhus** [comment]
Thanks for reporting. This is indeed a bug.
