### ISSUE TITLE
1.1.1 breaks multipart form boundary

### ISSUE THREAD

**Issue by etfz** [sindresorhus/ky#539]
Multipart boundary value in `Content-Type` header does not match that of the body. Works in 1.1.0.

```js
let formData = new FormData()
formData.append('name', '5')
return ky.post(`/api/user`, {
	body: formData,
})
```

```
POST /api/user HTTP/2
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
Content-Type: multipart/form-data; boundary=---------------------------1565952755359404003007232716
Content-Length: 174

-----------------------------350127340439298904923059468489
Content-Disposition: form-data; name="name"

5
-----------------------------350127340439298904923059468489--
```

**Comment by kdelmonte** [comment]
I'll take a look.

**Comment by spaceemotion** [comment]
Came across the same issue when a user reported file uploads no longer working in Firefox (which is via S3). Chrome still works however (and all other Chromium alternatives).

**Comment by sholladay** [comment]
So this issue only happens on Chromium?

We have a [test for this](https://github.com/sindresorhus/ky/blob/dd713b6212b185366009d2429347796e6bae97e1/test/browser.ts#L325-L355) that is currently passing.

At the moment, our browser tests only run against Chromium. However, we have the ability to test other browsers as well. We should probably add Firefox [here](https://github.com/sindresorhus/ky/blob/dd713b6212b185366009d2429347796e6bae97e1/test/helpers/with-page.ts#L10-L12). Just need to replace `playwright-chromium` with `playwright` and then `import { firefox } from 'playwright'`.

**Comment by kdelmonte** [comment]
Thanks for the guidance @sholladay. I can confirm this test indeed fails along with 4 others when using `import { firefox } from 'playwright'`.

<img width="856" alt="image" src="https://github.com/sindresorhus/ky/assets/900997/472febc1-546f-44df-a185-1b970e990cbb">

This test passes in 1.1.0 although I did find that some others do not:

<img width="856" alt="image" src="https://github.com/sindresorhus/ky/assets/900997/65c3109b-c756-4bda-bdec-058dbee86eff">

I am investigating now.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ky/releases/tag/v1.1.2
