### ISSUE TITLE
Add simple query/search parameters option?

### ISSUE THREAD

**Issue by mrtnbroder** [sindresorhus/ky#54]
I've added a very simple wrapper around fetch myself and added the ability to passing in a `qs` object, which adds some parameters to the url:
```js
const uri = new URL(url)
if (qs) {
	Object.keys(qs).forEach((key) => uri.searchParams.append(key, qs[key]))
}
```

it's a nicer api then just adding these to the url by hand.
I could make a PR if interested.

**Comment by sindresorhus** [comment]
Good idea! PR welcome. Should probably call the option `searchParams` to match the naming of the URL property.

I'm not sure whether it's a good idea to just append though. I would rather expect it to replace whatever's on the URL.

The `searchParams` option could be either an object, string, or URLSearchParams instance. Same as what `new URLSearchParams()` supports.

Thoughts?

**Comment by mrtnbroder** [comment]
> I'm not sure whether it's a good idea to just append though. I would rather expect it to replace whatever's on the URL.

I guess it depends on the API. Some expect array values as `a=foo&a=bar`, where others expect `a=foo,bar`. But I'm fine by using `.set` instead and go for the `a=foo,bar` approach (short = nicer!).

> The searchParams option could be either an object, string, or URLSearchParams instance. Same as what new URLSearchParams() supports.

Sounds good! maybe also add an alias for it like `sp` (searchParams) ? or `qs`? (which is more widely known I'd say). Opinions?
