### ISSUE TITLE
Tests are hanging

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ky#544]
https://github.com/sindresorhus/ky/actions/runs/6889948808

No idea why they suddenly started hanging.

**Comment by transitive-bullshit** [comment]
<img width="554" alt="CleanShot 2023-11-19 at 13 49 15@2x" src="https://github.com/sindresorhus/ky/assets/552829/e90ae2af-da46-4115-a005-91bd8dbfc406">


Could very likely be due to https://github.com/sindresorhus/ky/issues/535

**Comment by sindresorhus** [comment]
Fixed the CI in https://github.com/sindresorhus/ky/commit/634cb2b3ec8d949875c071fbc425f8724995fbf7
