### ISSUE TITLE
Ability to provide custom fetch

### ISSUE THREAD

**Issue by prichodko** [sindresorhus/ky#56]
I am loving the simplicity of this module. What I also love is [Next.js](https://github.com/zeit/next.js). However, those two unfortunately doesn't play well with each other. 

Trying to call `ky` inside Next's `getInitialProps` throws that `self` is not defined, because during first request `Next.js` calls `getInitialProps` on the server.

One possible solution would be to accept a user's `fetch` (e.g. https://www.npmjs.com/package/isomorphic-unfetch). 

I understand that this adds a complexity, but if you are willing to accept it, I can send a PR.

**Comment by sindresorhus** [comment]
Not sure I want to add an option for this, as it will enable users to supply a implementation that is not fully `Fetch`-compliant and then complain to me if something breaks. For example, `unfetch` is missing a lot and `node-fetch` is missing stuff too. I don't want to be forced to cater to those incomplete implementations.

**Comment by sindresorhus** [comment]
When #53 is fixed, you can just override the globals yourself with `node-fetch`.

**Comment by prichodko** [comment]
Haven't tried it yet, but I believe with the land of https://github.com/sindresorhus/ky/commit/f107e7b92d90e4b0287846a49ba3f30d9b9ca648 we can close this.
