### ISSUE TITLE
response.clone(...).arrayBuffer is not a function

### ISSUE THREAD

**Issue by filpoyma** [sindresorhus/ky#566]
I'm using ky in react native.
Works great until I enable the "network inspector" in React Native Debugger (https://github.com/jhen0409/react-native-debugger)
After this I get an exception error in the catch method after the GET request.
Error: response.clone(...).arrayBuffer is not a function.

Apple M1 Pro
MacOS: Ventura 13.0
React Native Debugger: 0.14.0
react-native: 0.72.6

**Comment by sholladay** [comment]
Is this still happening?

**Comment by sholladay** [comment]
Closing due to lack of response and reproducible example.
