### ISSUE TITLE
Content-Type detection

### ISSUE THREAD

**Issue by fregante** [sindresorhus/ky#567]
I'm manually doing content detection:

```ts
const response = await ky
  .post(tokenURL, {
    body: formData,
  })

switch (response.headers.get("Content-Type")) {
  case "application/json": {
    const parsed: AuthData = await response.json();
    // etc
  }

  case "application/x-www-form-urlencoded": {
    const parsed = await response.formData();
    // etc
  }

  default: {
    throw new TypeError(
      "Error getting OAuth2 token: unexpected response format",
    );
  }
}
```

Would it make sense to have an `.auto()` parser that deals with the content type automatically? JSON, FormData, Blob, etc. I think that's what Axios does for example (but it returns `unknown` as a type)

**Comment by fregante** [comment]
I don't know if it would bring substantial code improvements over the above code, but it would avoid having to figure out the various Content-Type strings

**Comment by sindresorhus** [comment]
How common is it to not know upfront what type you will be receiving? What is the use-case for such a thing?

**Comment by fregante** [comment]
Not very.

This specific scenario could be because it's a user-provided API endpoint. In reality APIs can also return "the wrong type", as seen in https://github.com/sindresorhus/ky/issues/375

So for example `.auto()` could handle both a proper JSON response and raw text, both of which would eventually be a valid "JsonValue"
