### ISSUE TITLE
Compatibility issue with Cloudflare Worker

### ISSUE THREAD

**Issue by lpellegr** [sindresorhus/ky#569]
Using ky 1.2.3 as follows in a Cloudflare Worker instance:

```
try {
    const response = await ky.post('https://api.ipregistry.co/?key=tryout', {
        json: ["AS1", "AS6", "AS42"],
        headers: {
            "Content-Type": "application/json"
        }
    }).json();

    console.log(response);
} catch (error) {
    console.error(error);
}
```

produces the following ouput and errors upon execution in a Cloudflare Worker runtime:

>  ✘ [ERROR] Your worker created multiple branches of a single stream (for instance, by calling `response.clone()` or `request.clone()`) but did not read the body of both branches. This is wasteful, as it forces the system to buffer the entire stream of data in memory, rather than streaming it through. This may cause your worker to be unexpectedly terminated for going over the memory limit. If you only meant to copy the request or response headers and metadata (e.g. in order to be able to modify them), use the appropriate constructors instead (for instance, `new Response(response.body, response)`, `new Request(request)`, etc).
> 
> 
> {
>   results: [
>     {
>       allocated: '2001-09-20T00:00:00.000+00:00',
>       asn: 1,
>       country_code: 'US',
>       domain: 'level3.com',
>       name: 'Level 3 Parent, LLC',
>       prefixes: [Object],
>       relationships: [Object],
>       registry: 'ARIN',
>       type: 'business',
>       updated: '2024-02-28T00:00:00.000+00:00'
>     },
>     {
>       allocated: '1984-02-02T00:00:00.000+00:00',
>       asn: 6,
>       country_code: 'US',
>       domain: 'atos.net',
>       name: 'Atos IT Solutions And Services, Inc.',
>       prefixes: [Object],
>       relationships: [Object],
>       registry: 'ARIN',
>       type: 'business',
>       updated: '2021-01-21T00:00:00.000+00:00'
>     },
>     {
>       allocated: '2001-05-16T00:00:00.000+00:00',
>       asn: 42,
>       country_code: 'US',
>       domain: 'pch.net',
>       name: 'Woodynet, Inc.',
>       prefixes: [Object],
>       relationships: [Object],
>       registry: 'ARIN',
>       type: 'business',
>       updated: '2012-03-02T00:00:00.000+00:00'
>     }
>   ]
> }
> ✘ [ERROR] Your worker created multiple branches of a single stream (for instance, by calling `response.clone()` or `request.clone()`) but did not read the body of both branches. This is wasteful, as it forces the system to buffer the entire stream of data in memory, rather than streaming it through. This may cause your worker to be unexpectedly terminated for going over the memory limit. If you only meant to copy the request or response headers and metadata (e.g. in order to be able to modify them), use the appropriate constructors instead (for instance, `new Response(response.body, response)`, `new Request(request)`, etc).
> 
> 
> ✘ [ERROR] Your worker created multiple branches of a single stream (for instance, by calling `response.clone()` or `request.clone()`) but did not read the body of both branches. This is wasteful, as it forces the system to buffer the entire stream of data in memory, rather than streaming it through. This may cause your worker to be unexpectedly terminated for going over the memory limit. If you only meant to copy the request or response headers and metadata (e.g. in order to be able to modify them), use the appropriate constructors instead (for instance, `new Response(response.body, response)`, `new Request(request)`, etc).

I have no idea about how to work around this. Any idea?

**Comment by riderx** [comment]
did you added this in wrangler config
`compatibility_flags = ["nodejs_compat"]`

**Comment by lpellegr** [comment]
Yes, it was.

**Comment by Blitss** [comment]
Any update here?

**Comment by sholladay** [comment]
We got rid of `.clone()` for the initial request in Ky 1.4.0, which may help some:
https://github.com/sindresorhus/ky/pull/601

However, we still clone the request in case we need to do a retry. I don't think there's any other way to do it, as we can't clone the request after the body has been read, so we need to do it ahead of time in case we need it. Please let me know if anyone comes up with a better way, though.

I'm closing this for now, as I don't think it's actionable.
