### ISSUE TITLE
Why I keep getting HTTPError when the throwHttpErrors is already set to `false`

### ISSUE THREAD

**Issue by nekochan0122** [sindresorhus/ky#572]
![Untitled](https://github.com/sindresorhus/ky/assets/47508893/5819c0b3-4bd5-4b79-9abe-5e15b2524956)

**Comment by nekochan0122** [comment]
I think this is the problem?
https://github.com/sindresorhus/ky/blob/ec6733c97e5a2649b3683d5529517605eb6ba2ad/source/core/Ky.ts#L143

**Comment by sindresorhus** [comment]
We have a test that shows it should be working, but I'm happy to look further into it if you submit a failing test.

https://github.com/sindresorhus/ky/blob/ec6733c97e5a2649b3683d5529517605eb6ba2ad/test/main.ts#L407-L416

**Comment by nekochan0122** [comment]
> We have a test that shows it should be working, but I'm happy to look further into it if you submit a failing test.
> 
> https://github.com/sindresorhus/ky/blob/ec6733c97e5a2649b3683d5529517605eb6ba2ad/test/main.ts#L407-L416

Sorry, the `throwHttpErrors` option is working, the Error was throw by other request.
