### ISSUE TITLE
beforeError hook isn't called on 500 responses

### ISSUE THREAD

**Issue by geoff-harper** [sindresorhus/ky#575]
Hey I've encountered an issue when receiving 500 server codes from an api. For whatever reason it doesn't seem like the `beforeError` hook gets called. The following instance isn't producing any logs in the console when I hit a 500.

```ts 
const api = ky.create({
    retry: 0,
    hooks: {
      beforeError: [
        (error) => {
          console.log('handleBeforeServerError');
        },
      ],
    },
  });
};
```

I've confirmed that the same code is fine for 404s and other 400 codes. Here are the raw response headers for the 500

```text
HTTP/2 500 
date: Wed, 17 Apr 2024 16:04:41 GMT
content-length: 0
strict-transport-security: max-age=31536000; includeSubDomains
X-Firefox-Spdy: h2
```

and the 404

```text
HTTP/2 404 
date: Wed, 17 Apr 2024 16:05:52 GMT
content-length: 0
access-control-allow-credentials: true
access-control-allow-origin: http://localhost:3000
vary: Origin
strict-transport-security: max-age=31536000; includeSubDomains
X-Firefox-Spdy: h2
```

**Comment by sindresorhus** [comment]
Does 404 work? What environment are you running in? Native Fetch or node-fetch?

We have a test to confirm it's working: https://github.com/sindresorhus/ky/blob/2d56baf6739a49655cbbe74b5083c0350511bbed/test/hooks.ts#L610-L640

**Comment by geoff-harper** [comment]
It's in native fetch and 404 is working. I can't imagine it would make a difference but I'm noticing it on a PUT req

**Comment by sholladay** [comment]
I am unable to reproduce this. Would you mind trying to make an example on [CodeSandbox](https://codesandbox.io), [StackBlitz](https://stackblitz.com), or [RunKit](https://runkit.com)?

Here is what I tried:

```js
import ky from 'https://esm.sh/ky@1';

let hookCalls = 0;
const api = ky.create({
    retry: 0,
    hooks: {
        beforeError: [
            (error) => {
                hookCalls++;
                console.log('hook call:', hookCalls);
            }
        ]
    }
});

await api.get('https://httpbin.org/status/500');
await api.post('https://httpbin.org/status/500');
await api.put('https://httpbin.org/status/500');
await api.patch('https://httpbin.org/status/500');
await api.head('https://httpbin.org/status/500');

console.log(hookCalls === 5);  // => true
```

My best guess at this point is either:
1. The HTTP server failed to close the connection after it errored, so `fetch()` is still waiting for the response to finish.
2. You accidentally used `ky` instead of `api`. I've made this mistake a number of times. 😄

**Comment by geoff-harper** [comment]
Looks like it was a server configuration issue on our end, I believe it's resolved now. Thanks for the check in
