### ISSUE TITLE
Progress events

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/ky#6]
We could use streams for that :)

**Comment by dangdennis** [comment]
By progress events, are you trying to replicate the same `downloadProgress` and `uploadProgress` events in the _got_ library?

**Comment by szmarczak** [comment]
Yup.

**Comment by sindresorhus** [comment]
Relevant: https://twitter.com/jaffathecake/status/1093072562819608576

**Comment by shresthapradip** [comment]
What about upload progress. For example if I want to show the upload progress as returned by server.
