### ISSUE TITLE
Consider extracting the HTTPError logic to an external module

### ISSUE THREAD

**Issue by fregante** [sindresorhus/ky#609]
I mentioned this in private before, but I think it might be beneficial to create a package with an API like:

```js
const response = fetch('/api');
if (!response.ok) 
	throw HTTPError.from(response);
```
```js
const response = fetch('/api');
throwIfHttpError(response);
```

**Comment by sindresorhus** [comment]
Yeah, I have an already almost finished package for this.

**Comment by sholladay** [comment]
`boom` has a lot of nice features, although it is optimized for server-side usage:
https://github.com/hapijs/boom

**Comment by sindresorhus** [comment]
@fregante https://github.com/sindresorhus/fetch-extras

Feedback welcome :)

**Comment by fregante** [comment]
Good idea to make a single utilities package, there might be more ☺️
