### ISSUE TITLE
Add generic for HTTPError to type the response

### ISSUE THREAD

**Issue by yslpn** [sindresorhus/ky#615]
Hello. I use ky with @tanstack/svelte-query, but sometimes when working with forms I need to type the error to pass it to the @tanstack/svelte-query library. 

For example:

```
export const useEditProfileMutation = (profileId: string) => {
  const client = useQueryClient();

  return createMutation<Profile, HTTPError<ValidationErrorsProfile>, Profile>({
    mutationFn: (profile: Profile) =>
      api.put(`member/${profileId}`, { json: profile }).json<Profile>(),
    onSuccess: () => {
      client.invalidateQueries({ queryKey: [QUERY_KEY_PROFILE, profileId] });
    },
  });
};

```

Generic for HTTPError that types KyResponse. It would be convenient.

```
export declare class HTTPError<T = unknown> extends Error {
    response: KyResponse<T>;
    request: KyRequest;
    options: NormalizedOptions;
    constructor(response: Response, request: Request, options: NormalizedOptions);
}
```

Or am I doing everything wrong and there is a right way?

**Comment by sholladay** [comment]
I can see the value in this and I don't really see a problem with it, other than a general feeling that passing a generic two layers down is too indirect. But I don't have a specific alternative to suggest.

**Comment by yslpn** [comment]
The great and terrible axios does this and allows you to type the error.  I
think this is best practice.

https://github.com/axios/axios/blob/v1.x/index.d.ts

`AxiosError<T = unknown, D = any>`

In any case, every developer is faced with the fact that he needs to work
with custom errors.
