### ISSUE TITLE
Question: Is XHR Supported

### ISSUE THREAD

**Issue by jdalrymple** [sindresorhus/ky#62]
From looking at the tags in the package.json file, I noticed it says XHR, but when looking at the actual repository's docs, it uses the browser fetch API. Does this mean this library does not support XHR?

**Comment by sindresorhus** [comment]
Yes, no XHR, only Fetch. You can use the Fetch polyfill in browsers that doesn't support Fetch.

**Comment by jdalrymple** [comment]
Ah good to know. Might want to remove xhr from the keywords to remove confusion in the future. Thanks for the quick response!
