### ISSUE TITLE
[Question] Does it support HTTP/2 ? (compraison with Got)

### ISSUE THREAD

**Issue by SirMishaa** [sindresorhus/ky#620]
Hello, 

Coming from the got repository page, I saw the following : 
![image](https://github.com/user-attachments/assets/8588b2d9-94ac-4a0c-b1b3-542e06d34067)

Is this still up to date ? HTTP/2 is pretty useful in terms of speed, so I wanted to know if KY support it before considering it for work.
I didn't find the answer, so sorry if it explained somewhere.

**Comment by sindresorhus** [comment]
Ky is based on `fetch`, and I believe `fetch` uses HTTP/2 in browsers. For Node.js, see: https://github.com/nodejs/undici/issues/2750

**Comment by sholladay** [comment]
Ky supports HTTP/2 and even HTTP/3. The environment just has to support it.

Here is a Ky request to an HTTP/3 server in Firefox.

```js
import ky from 'https://esm.sh/ky@1';

const page = await ky('/').text();
console.log(page);
```

<img width="500" alt="image" src="https://github.com/user-attachments/assets/7d1a87b3-0bdc-40b4-ba55-7736b286638a">

___

For browsers, the support is pretty good.

HTTP/2: https://caniuse.com/http2
HTTP/3: https://caniuse.com/http3
