### ISSUE TITLE
Change the default retry amount

### ISSUE THREAD

**Issue by quememo** [sindresorhus/ky#621]
I am using ky together with React Query, and I am delegating the handling of retries to React Query, so in all my uses of ky, I set the retry count to 0. However, it's easy to forget to change it inline sometimes. Is there any way to change the default value so that all calls that don't have the parameter set have a value of 0 instead of the library's default (which is 2)? I imagine something like a config that centralizes this kind of setting could do it

**Comment by sholladay** [comment]
Yes, just pass your config to `ky.extend(options)`

**Comment by quememo** [comment]
Thanks!
