### ISSUE TITLE
request.d.ts compile error for browsers

### ISSUE THREAD

**Issue by Kaishiyoku** [sindresorhus/ky#622]
When I try to build my project with `tsc && vite build` it fails due to the following exception:

```
node_modules/ky/distribution/types/request.d.ts:2:113 - error TS2694: Namespace 'global.NodeJS' has no exported member 'ArrayBufferView'.

2 type UndiciBodyInit = ArrayBuffer | AsyncIterable<Uint8Array> | Blob | FormData | Iterable<Uint8Array> | NodeJS.ArrayBufferView | URLSearchParams | null | string;
                                                                                                                  ~~~~~~~~~~~~~~~


Found 1 error in node_modules/ky/distribution/types/request.d.ts:2
```

**Comment by sholladay** [comment]
I think the `NodeJS` namespace can just be removed. Does it compile if you do that?

I'm not sure if that would cause a problem in Node, though.

**Comment by Kaishiyoku** [comment]
> I think the `NodeJS` namespace can just be removed. Does it compile if you do that?
> 
> I'm not sure if that would cause a problem in Node, though.

This works. But also don't know if this would break Node projects.

**Comment by sholladay** [comment]
Ky targets browsers first and foremost, so I think we should go ahead and make that change.

PR welcome. Otherwise I'll take care of it soon.
