### ISSUE TITLE
Error in Safari: TypeError: Object.hasOwn is not a function

### ISSUE THREAD

**Issue by Elliott-Hu** [sindresorhus/ky#629]
TypeError: Object.hasOwn is not a function. (In 'Object.hasOwn(incoming, property)', 'Object.hasOwn' is undefined)

<img width="911" alt="image" src="https://github.com/user-attachments/assets/9d3cd4ec-51d6-40e1-85c0-dece198c87a8">

**Comment by sindresorhus** [comment]
You need to run it in a newer Node.js version or browser.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn
