### ISSUE TITLE
headers prop missing

### ISSUE THREAD

**Issue by Venipa** [sindresorhus/ky#630]
somehow i'm missing the headers in the request options, after some research there should be one

![image](https://github.com/user-attachments/assets/57a0970b-ab63-4581-bcf6-deaa1ad4467c)
![image](https://github.com/user-attachments/assets/4c9c538e-e041-4631-9165-a8dcd8fafcb0)

environment:
- node 20.15.0
- azure functions based on node
- typescript 4.9.5

**Comment by sholladay** [comment]
Somehow, it's using the wrong type, `KyOptions`, for the options argument, instead of `Options`.

I just checked for such a mistake in our code or exported types and couldn't find any. It probably has something to do with your environment.

**Comment by Venipa** [comment]
ye updated to typescript 5, typings are working now 👍
