### ISSUE TITLE
Introduction of Object.hasOwn in Release 1.6.0

### ISSUE THREAD

**Issue by Berhart** [sindresorhus/ky#631]
As mentioned in the title, Release [1.6.0](https://github.com/sindresorhus/ky/compare/v1.5.0...v1.6.0) started using `Object.hasOwn`.
This turned out to be a breaking change since I'm restricted to run [Chrome up to version 89](https://caniuse.com/mdn-javascript_builtins_object_hasown) (<= ES2021).

Would it be possible to use any other implementation?

Thanks in advance

**Comment by sindresorhus** [comment]
From the readme:

> Ky targets modern browsers, Node.js, Bun, and Deno.

It's up to you to polyfill if you need to supports older browsers, or stay on the older version of Ky.
