### ISSUE TITLE
`timeout` option doesn't work when using `beforeRequest` (or other?) hooks

### ISSUE THREAD

**Issue by 0l1v3rr** [sindresorhus/ky#636]
Hello everyone,

I created a `ky` instance like this:
```ts
export const api = ky.create({
  prefixUrl: env.NEXT_PUBLIC_API_BASE,
  retry: { limit: 2, methods: ["get"] },
  hooks: {
    beforeRequest: [
      async (request) => {
        const token = await getToken();
        token && request.headers.set("Authorization", `Bearer ${token}`);
        return ky(request);
      },
    ],
  },
});
```

Then I send a POST request to an endpoint which takes more than 10 seconds to execute (10 seconds is the default timeout I believe), it gets cancelled after 10 seconds with the error `TimeoutError: Request timed out`. My code:
```ts
await api
      .post("endpoint", {
        body: objectToFormData({ image }),
        timeout: false,
      })
      .blob();
```
`timeout: false` should disable the timeout. 

After a few hours of debugging, I tried everything, then I removed the hooks from my `ky` instance. Now, it looks like this:
```ts
const api2 = ky.create({
  prefixUrl: env.NEXT_PUBLIC_API_BASE,
  retry: { limit: 2, methods: ["get"] },
});
```
Like this, the `timeout: false` works fine.

Has anyone ever faced this, or am I the one who's doing something incorrectly?

Thank you!

**Comment by sholladay** [comment]
It is your `getToken()` request that is timing it. You haven't disabled timeouts on that.

**Comment by 0l1v3rr** [comment]
And how can I pass the timeout from the outside, not when creating the instance but when calling it?

**Comment by sholladay** [comment]
Ky passes the options, including timeout, to hooks. So your hook function can take in timeout and do whatever it needs, such as passing it to unrelated Ky instances.

```js

export const api = ky.create({
  prefixUrl: env.NEXT_PUBLIC_API_BASE,
  retry: { limit: 2, methods: ["get"] },
  hooks: {
    beforeRequest: [
      async (request, {timeout}) => {
        const token = await getToken();
        token && request.headers.set("Authorization", `Bearer ${token}`);
        return ky(request, {timeout});
      },
    ],
  },
});
```

Now, you can run `api.post('/foo', {timeout: 5000})` and the `timeout` option for both requests will be `5000`.

**Comment by 0l1v3rr** [comment]
Thank you very much, it works!

I tried it before, but TypeScript cried because he thinks that the second parameter (`options`, with a type of `NormalizedOptions`) doesn't have a timeout property. But eventually, it worked:
```ts
export const api = ky.create({
  prefixUrl: env.NEXT_PUBLIC_API_BASE,
  retry: { limit: 2, methods: ["get"] },
  hooks: {
    beforeRequest: [
      async (request, options) => {
        const token = await getToken();
        token && request.headers.set("Authorization", `Bearer ${token}`);
        return ky(request, {
          timeout: (options as NormalizedOptions & { timeout?: number | false }).timeout,
        });
      },
    ],
  },
});
```

Another thing is that I don't see a similar example in the docs. Maybe I didn't look closely enough, but if it is not mentioned or shown anywhere, I think it would be worth documenting.

Thanks again!

**Comment by sholladay** [comment]
Glad to hear that it works for you. The TypeScript issue is weird, could be a bug.

I agree that adding it to the documentation could be useful. Feel free to send a PR.
