### ISSUE TITLE
Chrome latest version ky version 0.31.0  is getting this error TypeError: Cannot set property duplex of #<Request> which has only a getter

### ISSUE THREAD

**Issue by yadprab** [sindresorhus/ky#653]
we're using ky v0.31.0 our customers have updated to the latest version of chrome v131
after the update ky throws this error ` TypeError: Cannot set property duplex of #<Request> which has only a getter` we fixed it by upgrading to the latest version but we're trying to understading why this happened in the latest version of chrome

**Comment by yadprab** [comment]
> Original fix: #467
> 
> Looks like duplex was finally implemented in chrome 131 and this caused the break.
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Request#browser_compatibility

thank you so much

**Comment by sholladay** [comment]
Closing since this was fixed a long time ago in Ky 0.33.1.
