### ISSUE TITLE
How to load with browser / script tag?

### ISSUE THREAD

**Issue by pwFoo** [sindresorhus/ky#73]
Searching for a browser usable version like ky.js / ky.min.js or a way to load ky to get it work?
Haven't found (unpkg.com, repo, readme).

**Comment by pwFoo** [comment]
Also tested to load it as module like that.
```
<script type="module" src="https://unpkg.com/ky/index.js"></script>
```

I'm not experienced with that type of JS files / modules and most time just load "normal" js files, but "ky" is not defined.
````
<script src="https://unpkg.com/ky/index.js"></script>
```

**Comment by sindresorhus** [comment]
@pwFoo See #78

**Comment by pwFoo** [comment]
Thanks! I'll test it 👍
