### ISSUE TITLE
Searching for ky

### ISSUE THREAD

**Issue by JesusCrow** [sindresorhus/ky#75]
I have just spent 15 minutes, because I forgot `ky` name. Using keywords like `fetch`, `library`, `tiny` etc. I failed to find this library in google, npm and github. In the end I kept scrolling in my liked tweets until I found it.

**Comment by sholladay** [comment]
We've got the usual set of keywords in package.json and the repo is marked with a few GitHub "Topics". Probably needs more outside links for search engines to prioritize it (videos, blogs, tweets, etc).

**Comment by szmarczak** [comment]
Closing this for now. To find `ky` you can search `modern http client for browsers` in Google :)
