### ISSUE TITLE
`throwHttpErrors` option

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/ky#9]
It's always true. Let's make it an option so we can turn that off.

**Comment by killynathan** [comment]
Sorry for the inconvenience, but I am stuck on one thing. If i understand this issue correctly, if someone passes false for `throwHttpErrors`, then line 151:
```
const shouldRetryStatusCode = error instanceof HTTPError ? retryStatusCodes.has(error.response.status): true;
```
will evaluate to true every time, ignoring status code checks. Should I then replace line 151 with:
```
const shouldRetryStatusCode = error.response &&  retryStatusCodes.has(error.response.status);
```
Also, should I add a test and documentation for this option?

**Comment by szmarczak** [comment]
Yes, tests and documentation is needed.

There's nothing wrong with `shouldRetryStatusCode`, so I wouldn't change that. Instead, I would change:

https://github.com/sindresorhus/ky/blob/f15717572c33cf0b8013ec7e7fdee59a3f1ff76f/index.js#L156

to

```js
if (this._options.throwHttpErrors) {
    throw error;
}
```

Also you need to make `throwHttpErrors` true by default.
