### ISSUE TITLE
afterResponse hooks not fired if await ky directly

### ISSUE THREAD

**Issue by 7Pass** [sindresorhus/ky#94]
As discussed in Pr #93:
`afterResponse` hooks are not executed for the following code:

```js
const response = await ky.get('https://example.com', {
    hooks: {
        afterResponse: [
             response => {
                 // This won't get called
             }
         ]
     }
});

const data = await response.json();
```

I know this is not how `ky` is supposed to be used, but it's easy to fall into this and see that everything is working, except the hooks.

**Comment by sholladay** [comment]
Confirmed. From what I can see, the underlying problem also applies to our retry logic.

[This code](https://github.com/sindresorhus/ky/blob/d5d3eaa24f903294d1b86d96a7652262c61536eb/index.js#L187-L211) probably needs to be moved to a function and called both inside and outside of the loop.
