### ISSUE TITLE
DOCS: use data, not json for variable name

### ISSUE THREAD

**Issue by tracker1** [sindresorhus/ky#99]
It's a minor niggle, but would be better to use `data` for the variable holding the response in the documentation.  JSON is a serialization standard, and in code should always be a string containing a serialized value, not the deserialized object.

Instead of: `const json = await ky(url).json();`

Use: `const data = await ky(url).json()`

**Comment by szmarczak** [comment]
Or:

```
const parsed = await ky(url).json();
```
